__version__ = "6.2.11"
default_app_config = "kapt_catalog.apps.KaptCatalogRegistryConfig"

try:
    import kapt_apidae
    from packaging import version

    assert version.parse(kapt_apidae.__version__) >= version.parse(
        "1.5.0"
    ), f"""
    Since kapt-catalog 6.2.11, if kapt-apidae is used to fill the database, it
    must be kapt-apidae >= 1.5.0 ({kapt_apidae.__version__} found).

    Formerly in kapt-catalog, the slug field of an Activity was generated by a
    method which was dependant of kapt-apidae internal structure.

    Starting from kapt-catalog 6.2.11, the slug field is generated from a new
    `StructureReference.identifier` field, which has to be filled by the import
    script.

    Import script of kapt-apidae >= 1.5.0 manage this new field.
    """
except ImportError:
    ...
