
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-13T22:25:36-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "58b9693a28f86051b6c2aab5fbd26f39516b0921",
 "version": "3.1.13.dev3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
