
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-13T01:38:46.351418",
 "dirty": false,
 "error": null,
 "full-revisionid": "d90ea3e52655b9b58aaf884bb910fef79e0594c6",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
