from typing import Literal

PRELOAD_THUMBNAILS_ENV = 'PRELOAD_THUMBNAILS'
GENERATE_OPENAPI_SCHEMA_ON_STARTUP_ENV = 'GENERATE_OPENAPI_SCHEMA_ON_STARTUP'
LOG_SQL_ENV = 'LOG_SQL'
LOG_LEVEL_ENV = 'LOG_LEVEL'
DEVICE_ENV = 'DEVICE'
TRANSCRIPTION_MODEL_ENV = 'TRANSCRIPTION_MODEL'
RETRANSCRIBE_AUTO_TRANSCRIBED_ENV = 'RETRANSCRIBE_AUTO_TRANSCRIBED'

DIRECTORY_NAME_HEADER = 'X-Directory'

Language = Literal['pl', 'en']
SUPPORTED_LANGUAGES: list[Language] = ['pl', 'en']
