from pypanther.rules.aws_eks.source_ip_multiple_403 import AmazonEKSAuditMultiple403 as AmazonEKSAuditMultiple403
from pypanther.rules.aws_eks.system_namespace_public_ip import (
    AmazonEKSAuditSystemNamespaceFromPublicIP as AmazonEKSAuditSystemNamespaceFromPublicIP,
)
