# Generated by Django 5.1.2 on 2025-01-03 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_kitchenaimanagement_module_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmbedFunctionTokenCounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embedding_tokens", models.IntegerField(default=0)),
                ("total_llm_tokens", models.IntegerField(default=0)),
                ("llm_prompt_tokens", models.IntegerField(default=0)),
                ("llm_completion_tokens", models.IntegerField(default=0)),
                (
                    "embed_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.embedobject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StorageFunctionTokenCounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embedding_tokens", models.IntegerField(default=0)),
                ("llm_prompt_tokens", models.IntegerField(default=0)),
                ("llm_completion_tokens", models.IntegerField(default=0)),
                ("total_llm_tokens", models.IntegerField(default=0)),
                (
                    "file_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.fileobject",
                    ),
                ),
            ],
        ),
    ]
