
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-13T17:02:23+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0709d7093895e846ba5c3c8e1018749307e58d80",
 "version": "1.2.1-rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
