
tigrina_alphabets=['ሀ', 'ሁ', 'ሂ', 'ሃ', 'ሄ', 'ህ', 'ሆ', 'ለ', 'ሉ', 'ሊ', 'ላ', 'ሌ',
    'ል', 'ሎ', 'ሐ', 'ሑ', 'ሒ', 'ሓ', 'ሔ', 'ሕ', 'ሖ', 'መ', 'ሙ', 'ሚ',
    'ማ', 'ሜ', 'ም', 'ሞ', 'ሠ', 'ሡ', 'ሢ', 'ሣ', 'ሤ', 'ሥ', 'ሦ', 'ረ',
    'ሩ', 'ሪ', 'ራ', 'ሬ', 'ር', 'ሮ', 'ሰ', 'ሱ', 'ሲ', 'ሳ', 'ሴ', 'ስ',
    'ሶ', 'ሸ', 'ሹ', 'ሺ', 'ሻ', 'ሼ', 'ሽ', 'ሾ', 'ቀ', 'ቁ', 'ቂ', 'ቃ',
    'ቄ', 'ቅ', 'ቆ', 'ቐ', 'ቑ', 'ቒ', 'ቓ', 'ቔ', 'ቕ', 'ቖ', 'በ', 'ቡ',
    'ቢ', 'ባ', 'ቤ', 'ብ', 'ቦ', 'ቨ', 'ቩ', 'ቪ', 'ቫ', 'ቬ', 'ቭ', 'ቮ',
    'ተ', 'ቱ', 'ቲ', 'ታ', 'ቴ', 'ት', 'ቶ', 'ቸ', 'ቹ', 'ቺ', 'ቻ', 'ቼ',
    'ች', 'ቾ', 'ኀ', 'ኁ',
    'ኂ', 'ኃ', 'ኄ', 'ኅ', 'ኆ', 'ነ', 'ኑ', 'ኒ', 'ና', 'ኔ', 'ን',
    'ኖ', 'ኘ', 'ኙ', 'ኚ', 'ኛ', 'ኜ', 'ኝ', 'ኞ', 'አ', 'ኡ', 'ኢ', 'ኣ',
    'ኤ', 'እ', 'ኦ', 'ከ', 'ኩ', 'ኪ', 'ካ', 'ኬ', 'ክ', 'ኮ', 'ኸ', 'ኹ',
    'ኺ', 'ኻ', 'ኼ', 'ኽ', 'ኾ', 'ወ', 'ዉ', 'ዊ', 'ዋ', 'ዌ', 'ው', 'ዎ',
    'ዐ', 'ዑ', 'ዒ', 'ዓ', 'ዔ', 'ዕ', 'ዖ', 'ዘ', 'ዙ', 'ዚ', 'ዛ', 'ዜ',
    'ዝ', 'ዞ', 'ዠ', 'ዡ', 'ዢ', 'ዣ', 'ዤ', 'ዥ', 'ዦ', 'ደ', 'ዱ', 'ዲ',
    'ዳ', 'ዴ', 'ድ', 'ዶ', 'የ', 'ዩ', 'ዪ', 'ያ', 'ዬ', 'ይ', 'ዮ', 'ዸ',
    'ዹ', 'ዺ', 'ዻ', 'ዼ', 'ዽ', 'ዾ', 'ጀ', 'ጁ', 'ጂ', 'ጃ', 'ጄ', 'ጅ',
    'ጆ', 'ገ', 'ጉ', 'ጊ',
    'ጋ', 'ጌ', 'ግ', 'ጎ', 'ጘ', 'ጙ', 'ጚ', 'ጛ', 'ጜ', 'ጝ', 'ጞ',
    'ጠ', 'ጡ', 'ጢ', 'ጣ', 'ጤ', 'ጥ', 'ጦ', 'ጨ', 'ጩ', 'ጪ', 'ጫ', 'ጬ',
    'ጭ', 'ጮ', 'ጰ', 'ጱ', 'ጲ', 'ጳ', 'ጴ', 'ጵ', 'ጶ', 'ጸ', 'ጹ', 'ጺ',
    'ጻ', 'ጼ', 'ጽ', 'ጾ', 'ፀ', 'ፁ', 'ፂ', 'ፃ', 'ፄ', 'ፅ', 'ፆ', 'ፈ',
    'ፉ', 'ፊ', 'ፋ', 'ፌ', 'ፍ', 'ፎ', 'ፐ', 'ፑ', 'ፒ', 'ፓ', 'ፔ', 'ፕ',
    'ፖ', 'ቈ', 'ቊ', 'ቋ', 'ቌ', 'ቍ', 'ቊ', 'ቈ', 'ቘ', 'ቚ', 'ቛ', 'ቜ',
    'ቝ', 'ቚ', 'ቘ', 'ኈ', 'ኊ', 'ኋ', 'ኌ', 'ኍ', 'ኊ', 'ኈ', 'ኰ', 'ኲ',
    'ኳ', 'ኴ', 'ኵ', 'ኲ', 'ኰ', 'ዀ', 'ዂ', 'ዃ', 'ዄ', 'ዅ', 'ዂ', 'ዀ',
    'ጐ', 'ጒ', 'ጓ', 'ጔ', 'ጕ', 'ጒ', 'ጐ']

family_positions = [
    0,   7,  14,  21,  28,  35,  42,  49,  56,
    63,  70,  77,  84,  91,  98, 105, 112, 119,
    126, 133, 140, 147, 154, 161, 175, 168, 182,
    189, 196, 203, 210, 217, 224, 231, 238, 245,
    252, 259, 266, 273, 280, 287, 294
]


alphabet_structure= [
    '','ሀ', 'ሁ', 'ሂ', 'ሃ', 'ሄ', 'ህ', 'ሆ', 'ለ',
    'ሉ', '',  'ሊ', 'ላ', 'ሌ', 'ል', 'ሎ', 'ሐ', 'ሑ',
    'ሒ', 'ሓ', '',  'ሔ', 'ሕ', 'ሖ', 'መ', 'ሙ', 'ሚ',
    'ማ', 'ሜ', 'ም', '',  'ሞ', 'ሠ', 'ሡ', 'ሢ', 'ሣ',
    'ሤ', 'ሥ', 'ሦ', 'ረ', '',  'ሩ', 'ሪ', 'ራ', 'ሬ',
    'ር', 'ሮ', 'ሰ', 'ሱ', 'ሲ', '',  'ሳ', 'ሴ', 'ስ', 'ሶ', 'ሸ', 'ሹ', 'ሺ', 'ሻ',
    'ሼ', '',  'ሽ', 'ሾ', 'ቀ', 'ቁ', 'ቂ', 'ቃ', 'ቄ',
    'ቅ', 'ቆ', '',  'ቐ', 'ቑ', 'ቒ', 'ቓ', 'ቔ', 'ቕ',
    'ቖ', 'በ', 'ቡ', '',  'ቢ', 'ባ', 'ቤ', 'ብ', 'ቦ',
    'ቨ', 'ቩ', 'ቪ', 'ቫ', '',  'ቬ', 'ቭ', 'ቮ', 'ተ',
    'ቱ', 'ቲ', 'ታ', 'ቴ', 'ት', '',  '',  '',  '',  '',  '',  '',  '',  '',
    '',  '',  'ቶ', 'ቸ', 'ቹ', 'ቺ', 'ቻ', 'ቼ', 'ች',
    'ቾ', 'ኀ', '',  'ኁ', 'ኂ', 'ኃ', 'ኄ', 'ኅ', 'ኆ',
    'ነ', 'ኑ', 'ኒ', '',  'ና', 'ኔ', 'ን', 'ኖ', 'ኘ',
    'ኙ', 'ኚ', 'ኛ', 'ኜ', '',  'ኝ', 'ኞ', 'አ', 'ኡ',
    'ኢ', 'ኣ', 'ኤ', 'እ', 'ኦ','',  'ከ', 'ኩ', 'ኪ', 'ካ', 'ኬ', 'ክ', 'ኮ', 'ኸ',
    'ኹ', '',  'ኺ', 'ኻ', 'ኼ', 'ኽ', 'ኾ', 'ወ', 'ዉ',
    'ዊ', 'ዋ', '',  'ዌ', 'ው', 'ዎ', 'ዐ', 'ዑ', 'ዒ',
    'ዓ', 'ዔ', 'ዕ', '',  'ዖ', 'ዘ', 'ዙ', 'ዚ', 'ዛ',
    'ዜ', 'ዝ', 'ዞ', 'ዠ', '',  'ዡ', 'ዢ', 'ዣ', 'ዤ',
    'ዥ', 'ዦ', 'ደ', 'ዱ', 'ዲ', '',  '',  '',  '',  '',  '',  '',  '',  '',
    '',  '',  '',  'ዳ', 'ዴ', 'ድ', 'ዶ', 'የ', 'ዩ',
    'ዪ', 'ያ', '',  'ዬ', 'ይ', 'ዮ', 'ዸ', 'ዹ', 'ዺ',
    'ዻ', 'ዼ', 'ዽ', '',  'ዾ', 'ጀ', 'ጁ', 'ጂ', 'ጃ',
    'ጄ', 'ጅ', 'ጆ', 'ገ', '',  'ጉ', 'ጊ', 'ጋ', 'ጌ',
    'ግ', 'ጎ', 'ጘ', 'ጙ', 'ጚ', '',  'ጛ', 'ጜ', 'ጝ', 'ጞ', 'ጠ', 'ጡ', 'ጢ', 'ጣ',
    'ጤ', '',  'ጥ', 'ጦ', 'ጨ', 'ጩ', 'ጪ', 'ጫ', 'ጬ',
    'ጭ', 'ጮ', '',  'ጰ', 'ጱ', 'ጲ', 'ጳ', 'ጴ', 'ጵ',
    'ጶ', 'ጸ', 'ጹ', '',  'ጺ', 'ጻ', 'ጼ', 'ጽ', 'ጾ',
    'ፀ', 'ፁ', 'ፂ', 'ፃ', '',  'ፄ', 'ፅ', 'ፆ', 'ፈ',
    'ፉ', 'ፊ', 'ፋ', 'ፌ', 'ፍ', '',  '',  '',  '',  '',  '',  '',  '',  '',
    '',  '',  'ፎ', 'ፐ', 'ፑ', 'ፒ', 'ፓ', 'ፔ', 'ፕ',
    'ፖ', 'ቈ', '',  'ቊ', 'ቋ', 'ቌ', 'ቍ', 'ቊ', 'ቈ',
    'ቘ', 'ቚ', 'ቛ', '',  'ቜ', 'ቝ', 'ቚ', 'ቘ', 'ኈ',
    'ኊ', 'ኋ', 'ኌ', 'ኍ', '',  'ኊ', 'ኈ', 'ኰ', 'ኲ',
    'ኳ', 'ኴ', 'ኵ', 'ኲ', 'ኰ','',  'ዀ', 'ዂ', 'ዃ', 'ዄ', 'ዅ', 'ዂ', 'ዀ', 'ጐ',
    'ጒ', '',  'ጓ', 'ጔ', 'ጕ', 'ጒ', 'ጐ', 'a', 'b',
    'c', 'd', '',  'e', 'f','g', 'j', 'h', 'i', 'j',
    'k', 'l','', 'm', 'n', 'o', 'p', 'q', 'r',
    's', 't', 'u','', 'v', 'w', 'x', 'y', 'z',
    'A', 'B', 'C', 'D', '','','','','','','','','','','','','E', 'F', 'G', 'H', 'I', 'J',
    'K', 'L', 'M','', 'N', 'O', 'P', 'Q',
    'R', 'S', 'T', 'U', 'V','', 'W', 'X',
    'Y', 'Z', ' ',''
]

family_start_to_end_positions= [
    [ 1, 7 ],     [ 8, 15 ],    [ 16, 23 ],
    [ 24, 31 ],   [ 32, 38 ],   [ 39, 46 ],
    [ 47, 54 ],   [ 55, 62 ],   [ 63, 69 ],
    [ 71, 77 ],   [ 78, 85 ],   [ 86, 93 ],
    [ 94, 111 ],  [ 112, 118 ], [ 119, 126 ],
    [ 127, 134 ], [ 135, 142 ], [ 143, 149 ],
    [ 151, 157 ], [ 158, 165 ], [ 166, 173 ],
    [ 174, 181 ], [ 182, 188 ], [ 189, 196 ],
    [ 216, 223 ], [ 197, 215 ], [ 224, 231 ],
    [ 232, 238 ], [ 239, 246 ], [ 247, 254 ],
    [ 255, 262 ], [ 263, 269 ], [ 271, 277 ],
    [ 278, 285 ], [ 286, 293 ], [ 294, 311 ],
    [ 312, 318 ], [ 319, 321 ], [ 327, 328 ],
    [ 335, 336 ], [ 343, 344 ], [ 351, 352 ],
    [ 358, 359 ]
]
begining_word_additions=["ኣብዝ","ኣብት","ኣብን","ብዝ","ብት","ብን","ምስዝ","ምስት",'እንተ',"እንተዝ","እንተዘ","እንተት","ምስዘይ","ከምዘይ"]
last_word_additions=["ሉ","ካ","ኪ","ም","ን","ና","ክን","ኩም","ካሉ","ኪሉ","ክንሉ","ኩምሉ","ትሉ","ምሉ","ንሉ","ናሉ","ዮ","ዎ","ቶ","ሞ","ንኦ","ናዮ","ካዮ","ኪዮ","ክንኦ","ክምዎ","ያ","ዋ","ታ","ማ","ንኣ","ኩማ","ካያ","ኪያ","ክንኣ","ኩማ" ,"ኒ" ,"ኒ" ,"ትኒ" ,"ምኒ" ,"ናኒ" ,"ኩምኒ" ,"ካኒ" ,"ክኒ" ,"ክናኒ" ,"ኩምኒ","ሙኒ","ሞ"
    ,"ማ","ሞም","መን","ኩመን","ካዮም","ክዮም","ክንኦም","ኩሞም","ናኒ","ነኦ","ናኣ","ነኦም","ነአን","ኹም","ናኻ","ናኺ","ናኽን" ,"ናኹም","ኩምኒ","ኩሞ","ማ","ሞም","ኩመን","ኩሞም","ሙኻ","ሙኺ","ሙኽን" ,"ሙኹም"
    ,"ካኒ","ካዮ","ካያ","ካዮም","ካየን","ካዮም","ካዮ","ካያ","ካየን" ,"ካዮም","ኩምኒ","ኩሞ","ኩማ","ኩሞም","ኩመን","ኩምና","ኩሞ","ኩማ","ኩመን" ,"ኩሞም","ክኒ","ክዮ","ክያ","ክዮም","ክየን","ክዮም","ክዮ","ክያ"
    ,"ክየም","ክዮም","ክናኒ","ክንኦ","ክንኣ","ክንኦም","ክንአን","ክንኦም","ክንኦ","ክንኣ","ክንአን" ,"ክንኦም"]

tigrina_english_aphabets = [
    { "key": "ሀ", "value": "he", "position": 1, "family": "ሀ", "order": 51 },
    { "key": "ሁ", "value": "hu", "position": 2, "family": "ሀ", "order": 52 },
    { "key": "ሂ", "value": "hi", "position": 3, "family": "ሀ", "order": 53 },
    { "key": "ሃ", "value": "ha", "position": 4, "family": "ሀ", "order": 54 },
    { "key": "ሄ", "value": "hie", "position": 5, "family": "ሀ", "order": 55 },
    { "key": "ህ", "value": "h", "position": 6, "family": "ሀ", "order": 56 },
    { "key": "ሆ", "value": "ho", "position": 7, "family": "ሀ", "order": 57 },
    { "key": "ለ", "value": "le", "position": 1, "family": "ለ", "order": 58 },
    { "key": "ሉ", "value": "lu", "position": 2, "family": "ለ", "order": 59 },
    { "key": "ሊ", "value": "li", "position": 3, "family": "ለ", "order": 60 },
    { "key": "ላ", "value": "la", "position": 4, "family": "ለ", "order": 61 },
    { "key": "ሌ", "value": "lie", "position": 5, "family": "ለ", "order": 62 },
    { "key": "ል", "value": "l", "position": 6, "family": "ለ", "order": 63 },
    { "key": "ሎ", "value": "lo", "position": 7, "family": "ለ", "order": 64 },
    { "key": "ሐ", "value": "He", "position": 1, "family": "ሐ", "order": 65 },
    { "key": "ሑ", "value": "Hu", "position": 2, "family": "ሐ", "order": 66 },
    { "key": "ሒ", "value": "Hi", "position": 3, "family": "ሐ", "order": 67 },
    { "key": "ሓ", "value": "Ha", "position": 4, "family": "ሐ", "order": 68 },
    { "key": "ሔ", "value": "Hie", "position": 5, "family": "ሐ", "order": 69 },
    { "key": "ሕ", "value": "H", "position": 6, "family": "ሐ", "order": 70 },
    { "key": "ሖ", "value": "Ho", "position": 7, "family": "ሐ", "order": 71 },
    { "key": "መ", "value": "me", "position": 1, "family": "መ", "order": 72 },
    { "key": "ሙ", "value": "mu", "position": 2, "family": "መ", "order": 73 },
    { "key": "ሚ", "value": "mi", "position": 3, "family": "መ", "order": 74 },
    { "key": "ማ", "value": "ma", "position": 4, "family": "መ", "order": 75 },
    { "key": "ሜ", "value": "mie", "position": 5, "family": "መ", "order": 76 },
    { "key": "ም", "value": "m", "position": 6, "family": "መ", "order": 77 },
    { "key": "ሞ", "value": "mo", "position": 7, "family": "መ", "order": 78 },
    { "key": "ሠ", "value": "s2e", "position": 1, "family": "ሠ", "order": 79 },
    { "key": "ሡ", "value": "s2u", "position": 2, "family": "ሠ", "order": 80 },
    { "key": "ሢ", "value": "s2i", "position": 3, "family": "ሠ", "order": 81 },
    { "key": "ሣ", "value": "s2a", "position": 4, "family": "ሠ", "order": 82 },
    { "key": "ሤ", "value": "s2ie", "position": 5, "family": "ሠ", "order": 83 },
    { "key": "ሥ", "value": "s2", "position": 6, "family": "ሠ", "order": 84 },
    { "key": "ሦ", "value": "s2o", "position": 7, "family": "ሠ", "order": 85 },
    { "key": "ረ", "value": "re", "position": 1, "family": "ረ", "order": 86 },
    { "key": "ሩ", "value": "ru", "position": 2, "family": "ረ", "order": 87 },
    { "key": "ሪ", "value": "ri", "position": 3, "family": "ረ", "order": 88 },
    { "key": "ራ", "value": "ra", "position": 4, "family": "ረ", "order": 89 },
    { "key": "ሬ", "value": "rie", "position": 5, "family": "ረ", "order": 90 },
    { "key": "ር", "value": "r", "position": 6, "family": "ረ", "order": 91 },
    { "key": "ሮ", "value": "ro", "position": 7, "family": "ረ", "order": 92 },
    { "key": "ሰ", "value": "se", "position": 1, "family": "ሰ", "order": 93 },
    { "key": "ሱ", "value": "su", "position": 2, "family": "ሰ", "order": 94 },
    { "key": "ሲ", "value": "si", "position": 3, "family": "ሰ", "order": 95 },
    { "key": "ሳ", "value": "sa", "position": 4, "family": "ሰ", "order": 96 },
    { "key": "ሴ", "value": "sie", "position": 5, "family": "ሰ", "order": 97 },
    { "key": "ስ", "value": "s", "position": 6, "family": "ሰ", "order": 98 },
    { "key": "ሶ", "value": "so", "position": 7, "family": "ሰ", "order": 99 },
    { "key": "ሸ", "value": "Se", "position": 1, "family": "ሸ", "order": 100 },
    { "key": "ሹ", "value": "Su", "position": 2, "family": "ሸ", "order": 101 },
    { "key": "ሺ", "value": "Si", "position": 3, "family": "ሸ", "order": 102 },
    { "key": "ሻ", "value": "Sa", "position": 4, "family": "ሸ", "order": 103 },
    { "key": "ሼ", "value": "Sie", "position": 5, "family": "ሸ", "order": 104 },
    { "key": "ሽ", "value": "S", "position": 6, "family": "ሸ", "order": 105 },
    { "key": "ሾ", "value": "So", "position": 7, "family": "ሸ", "order": 106 },
    { "key": "ቀ", "value": "qe", "position": 1, "family": "ቀ", "order": 107 },
    { "key": "ቁ", "value": "qu", "position": 2, "family": "ቀ", "order": 108 },
    { "key": "ቂ", "value": "qi", "position": 3, "family": "ቀ", "order": 109 },
    { "key": "ቃ", "value": "qa", "position": 4, "family": "ቀ", "order": 110 },
    { "key": "ቄ", "value": "qie", "position": 5, "family": "ቀ", "order": 111 },
    { "key": "ቅ", "value": "q", "position": 6, "family": "ቀ", "order": 112 },
    { "key": "ቆ", "value": "qo", "position": 7, "family": "ቀ", "order": 113 },
    { "key": "ቐ", "value": "Qe", "position": 1, "family": "ቐ", "order": 114 },
    { "key": "ቑ", "value": "Qu", "position": 2, "family": "ቐ", "order": 115 },
    { "key": "ቒ", "value": "Qi", "position": 3, "family": "ቐ", "order": 116 },
    { "key": "ቓ", "value": "Qa", "position": 4, "family": "ቐ", "order": 117 },
    { "key": "ቔ", "value": "Qie", "position": 5, "family": "ቐ", "order": 118 },
    { "key": "ቕ", "value": "Q", "position": 6, "family": "ቐ", "order": 119 },
    { "key": "ቖ", "value": "Qo", "position": 7, "family": "ቐ", "order": 120 },
    { "key": "በ", "value": "be", "position": 1, "family": "በ", "order": 121 },
    { "key": "ቡ", "value": "bu", "position": 2, "family": "በ", "order": 122 },
    { "key": "ቢ", "value": "bi", "position": 3, "family": "በ", "order": 123 },
    { "key": "ባ", "value": "ba", "position": 4, "family": "በ", "order": 124 },
    { "key": "ቤ", "value": "bie", "position": 5, "family": "በ", "order": 125 },
    { "key": "ብ", "value": "b", "position": 6, "family": "በ", "order": 126 },
    { "key": "ቦ", "value": "bo", "position": 7, "family": "በ", "order": 127 },
    { "key": "ቨ", "value": "ve", "position": 1, "family": "ቨ", "order": 128 },
    { "key": "ቩ", "value": "vu", "position": 2, "family": "ቨ", "order": 129 },
    { "key": "ቪ", "value": "vi", "position": 3, "family": "ቨ", "order": 130 },
    { "key": "ቫ", "value": "va", "position": 4, "family": "ቨ", "order": 131 },
    { "key": "ቬ", "value": "vie", "position": 5, "family": "ቨ", "order": 132 },
    { "key": "ቭ", "value": "v", "position": 6, "family": "ቨ", "order": 133 },
    { "key": "ቮ", "value": "vo", "position": 7, "family": "ቨ", "order": 134 },
    { "key": "ተ", "value": "te", "position": 1, "family": "ተ", "order": 135 },
    { "key": "ቱ", "value": "tu", "position": 2, "family": "ተ", "order": 136 },
    { "key": "ቲ", "value": "ti", "position": 3, "family": "ተ", "order": 137 },
    { "key": "ታ", "value": "ta", "position": 4, "family": "ተ", "order": 138 },
    { "key": "ቴ", "value": "tie", "position": 5, "family": "ተ", "order": 139 },
    { "key": "ት", "value": "t", "position": 6, "family": "ተ", "order": 140 },
    { "key": "ቶ", "value": "to", "position": 7, "family": "ተ", "order": 141 },
    { "key": "ቸ", "value": "ce", "position": 1, "family": "ቸ", "order": 142 },
    { "key": "ቹ", "value": "cu", "position": 2, "family": "ቸ", "order": 143 },
    { "key": "ቺ", "value": "ci", "position": 3, "family": "ቸ", "order": 144 },
    { "key": "ቻ", "value": "ca", "position": 4, "family": "ቸ", "order": 145 },
    { "key": "ቼ", "value": "cie", "position": 5, "family": "ቸ", "order": 146 },
    { "key": "ች", "value": "c", "position": 6, "family": "ቸ", "order": 147 },
    { "key": "ቾ", "value": "co", "position": 7, "family": "ቸ", "order": 148 },
    { "key": "ነ", "value": "ne", "position": 1, "family": "ነ", "order": 149 },
    { "key": "ኑ", "value": "nu", "position": 2, "family": "ነ", "order": 150 },
    { "key": "ኒ", "value": "ni", "position": 3, "family": "ነ", "order": 151 },
    { "key": "ና", "value": "na", "position": 4, "family": "ነ", "order": 152 },
    { "key": "ኔ", "value": "nie", "position": 5, "family": "ነ", "order": 153 },
    { "key": "ን", "value": "n", "position": 6, "family": "ነ", "order": 154 },
    { "key": "ኖ", "value": "no", "position": 7, "family": "ነ", "order": 155 },
    { "key": "ኘ", "value": "Ne", "position": 1, "family": "ኘ", "order": 156 },
    { "key": "ኙ", "value": "Nu", "position": 2, "family": "ኘ", "order": 157 },
    { "key": "ኚ", "value": "Ni", "position": 3, "family": "ኘ", "order": 158 },
    { "key": "ኛ", "value": "Na", "position": 4, "family": "ኘ", "order": 159 },
    { "key": "ኜ", "value": "Nie", "position": 5, "family": "ኘ", "order": 160 },
    { "key": "ኝ", "value": "N", "position": 6, "family": "ኘ", "order": 161 },
    { "key": "ኞ", "value": "No", "position": 7, "family": "ኘ", "order": 162 },
    { "key": "አ", "value": "e", "position": 1, "family": "አ", "order": 163 },
    { "key": "ኡ", "value": "u", "position": 2, "family": "አ", "order": 164 },
    { "key": "ኢ", "value": "i", "position": 3, "family": "አ", "order": 165 },
    { "key": "ኣ", "value": "a", "position": 4, "family": "አ", "order": 166 },
    { "key": "ኤ", "value": "ie", "position": 5, "family": "አ", "order": 167 },
    { "key": "እ", "value": "A", "position": 6, "family": "አ", "order": 168 },
    { "key": "ኦ", "value": "o", "position": 7, "family": "አ", "order": 169 },
    { "key": "ከ", "value": "ke", "position": 1, "family": "ከ", "order": 170 },
    { "key": "ኩ", "value": "ku", "position": 2, "family": "ከ", "order": 171 },
    { "key": "ኪ", "value": "ki", "position": 3, "family": "ከ", "order": 172 },
    { "key": "ካ", "value": "ka", "position": 4, "family": "ከ", "order": 173 },
    { "key": "ኬ", "value": "kie", "position": 5, "family": "ከ", "order": 174 },
    { "key": "ክ", "value": "k", "position": 6, "family": "ከ", "order": 175 },
    { "key": "ኮ", "value": "ko", "position": 7, "family": "ከ", "order": 176 },
    { "key": "ኸ", "value": "Ke", "position": 1, "family": "ኸ", "order": 177 },
    { "key": "ኹ", "value": "Ku", "position": 2, "family": "ኸ", "order": 178 },
    { "key": "ኺ", "value": "Ki", "position": 3, "family": "ኸ", "order": 179 },
    { "key": "ኻ", "value": "Ka", "position": 4, "family": "ኸ", "order": 180 },
    { "key": "ኼ", "value": "Kie", "position": 5, "family": "ኸ", "order": 181 },
    { "key": "ኽ", "value": "K", "position": 6, "family": "ኸ", "order": 182 },
    { "key": "ኾ", "value": "Ko", "position": 7, "family": "ኸ", "order": 183 },
    { "key": "ወ", "value": "we", "position": 1, "family": "ወ", "order": 184 },
    { "key": "ዉ", "value": "wu", "position": 2, "family": "ወ", "order": 185 },
    { "key": "ዊ", "value": "wi", "position": 3, "family": "ወ", "order": 186 },
    { "key": "ዋ", "value": "wa", "position": 4, "family": "ወ", "order": 187 },
    { "key": "ዌ", "value": "wie", "position": 5, "family": "ወ", "order": 188 },
    { "key": "ው", "value": "w", "position": 6, "family": "ወ", "order": 189 },
    { "key": "ዎ", "value": "wo", "position": 7, "family": "ወ", "order": 190 },
    { "key": "ዐ", "value": "Oe", "position": 1, "family": "ዐ", "order": 191 },
    { "key": "ዑ", "value": "Ou", "position": 2, "family": "ዐ", "order": 192 },
    { "key": "ዒ", "value": "Oi", "position": 3, "family": "ዐ", "order": 193 },
    { "key": "ዓ", "value": "Oa", "position": 4, "family": "ዐ", "order": 194 },
    { "key": "ዔ", "value": "Oie", "position": 5, "family": "ዐ", "order": 195 },
    { "key": "ዕ", "value": "O", "position": 6, "family": "ዐ", "order": 196 },
    { "key": "ዖ", "value": "Oo", "position": 7, "family": "ዐ", "order": 197 },
    { "key": "ዘ", "value": "ze", "position": 1, "family": "ዘ", "order": 198 },
    { "key": "ዙ", "value": "zu", "position": 2, "family": "ዘ", "order": 199 },
    { "key": "ዚ", "value": "zi", "position": 3, "family": "ዘ", "order": 200 },
    { "key": "ዛ", "value": "za", "position": 4, "family": "ዘ", "order": 201 },
    { "key": "ዜ", "value": "zie", "position": 5, "family": "ዘ", "order": 202 },
    { "key": "ዝ", "value": "z", "position": 6, "family": "ዘ", "order": 203 },
    { "key": "ዞ", "value": "zo", "position": 7, "family": "ዘ", "order": 204 },
    { "key": "ዠ", "value": "Je", "position": 1, "family": "ዠ", "order": 205 },
    { "key": "ዡ", "value": "Ju", "position": 2, "family": "ዠ", "order": 206 },
    { "key": "ዢ", "value": "Ji", "position": 3, "family": "ዠ", "order": 207 },
    { "key": "ዣ", "value": "Ja", "position": 4, "family": "ዠ", "order": 208 },
    { "key": "ዤ", "value": "Jie", "position": 5, "family": "ዠ", "order": 209 },
    { "key": "ዥ", "value": "J", "position": 6, "family": "ዠ", "order": 210 },
    { "key": "ዦ", "value": "Jo", "position": 7, "family": "ዠ", "order": 211 },
    { "key": "ደ", "value": "de", "position": 1, "family": "ደ", "order": 212 },
    { "key": "ዱ", "value": "du", "position": 2, "family": "ደ", "order": 213 },
    { "key": "ዲ", "value": "di", "position": 3, "family": "ደ", "order": 214 },
    { "key": "ዳ", "value": "da", "position": 4, "family": "ደ", "order": 215 },
    { "key": "ዴ", "value": "die", "position": 5, "family": "ደ", "order": 216 },
    { "key": "ድ", "value": "d", "position": 6, "family": "ደ", "order": 217 },
    { "key": "ዶ", "value": "do", "position": 7, "family": "ደ", "order": 218 },
    { "key": "የ", "value": "ye", "position": 1, "family": "የ", "order": 219 },
    { "key": "ዩ ", "value": "yu", "position": 2, "family": "የ", "order": 220 },
    { "key": "ዪ", "value": "yi", "position": 3, "family": "የ", "order": 221 },
    { "key": "ያ", "value": "ya", "position": 4, "family": "የ", "order": 222 },
    { "key": "ዬ", "value": "yie", "position": 5, "family": "የ", "order": 223 },
    { "key": "ይ", "value": "y", "position": 6, "family": "የ", "order": 224 },
    { "key": "ዮ", "value": "yo", "position": 7, "family": "የ", "order": 225 },
    { "key": "ዸ", "value": "Pe", "position": 1, "family": "ዸ", "order": 226 },
    { "key": "ዹ", "value": "Pu", "position": 2, "family": "ዸ", "order": 227 },
    { "key": "ዺ", "value": "Pi", "position": 3, "family": "ዸ", "order": 228 },
    { "key": "ዻ", "value": "Pa", "position": 4, "family": "ዸ", "order": 229 },
    { "key": "ዼ", "value": "Pie", "position": 5, "family": "ዸ", "order": 230 },
    { "key": "ዽ", "value": "P", "position": 6, "family": "ዸ", "order": 231 },
    { "key": "ዾ", "value": "Po", "position": 7, "family": "ዸ", "order": 232 },
    { "key": "ጀ", "value": "je", "position": 1, "family": "ጀ", "order": 233 },
    { "key": "ጁ", "value": "ju", "position": 2, "family": "ጀ", "order": 234 },
    { "key": "ጂ", "value": "ji", "position": 3, "family": "ጀ", "order": 235 },
    { "key": "ጃ", "value": "ja", "position": 4, "family": "ጀ", "order": 236 },
    { "key": "ጄ", "value": "jie", "position": 5, "family": "ጀ", "order": 237 },
    { "key": "ጅ", "value": "j", "position": 6, "family": "ጀ", "order": 238 },
    { "key": "ጆ", "value": "jo", "position": 7, "family": "ጀ", "order": 239 },
    { "key": "ገ", "value": "ge", "position": 1, "family": "ገ", "order": 240 },
    { "key": "ጉ", "value": "gu", "position": 2, "family": "ገ", "order": 241 },
    { "key": "ጊ", "value": "gi", "position": 3, "family": "ገ", "order": 242 },
    { "key": "ጋ", "value": "ga", "position": 4, "family": "ገ", "order": 243 },
    { "key": "ጌ", "value": "gie", "position": 5, "family": "ገ", "order": 244 },
    { "key": "ግ", "value": "g", "position": 6, "family": "ገ", "order": 245 },
    { "key": "ጎ", "value": "go", "position": 7, "family": "ገ", "order": 246 },
    { "key": "ጠ", "value": "Te", "position": 1, "family": "ጠ", "order": 247 },
    { "key": "ጡ", "value": "Tu", "position": 2, "family": "ጠ", "order": 248 },
    { "key": "ጢ", "value": "Ti", "position": 3, "family": "ጠ", "order": 249 },
    { "key": "ጣ", "value": "Ta", "position": 4, "family": "ጠ", "order": 250 },
    { "key": "ጤ", "value": "Tie", "position": 5, "family": "ጠ", "order": 251 },
    { "key": "ጥ", "value": "T", "position": 6, "family": "ጠ", "order": 252 },
    { "key": "ጦ", "value": "To", "position": 7, "family": "ጠ", "order": 253 },
    { "key": "ጨ", "value": "c", "position": 1, "family": "ጨ", "order": 254 },
    { "key": "ጩ", "value": "ce", "position": 2, "family": "ጨ", "order": 255 },
    { "key": "ጪ", "value": "ci", "position": 3, "family": "ጨ", "order": 256 },
    { "key": "ጫ", "value": "ca", "position": 4, "family": "ጨ", "order": 257 },
    { "key": "ጬ", "value": "cie", "position": 5, "family": "ጨ", "order": 258 },
    { "key": "ጭ", "value": "c", "position": 6, "family": "ጨ", "order": 259 },
    { "key": "ጮ", "value": "co", "position": 7, "family": "ጨ", "order": 260 },
    { "key": "ጸ", "value": "xe", "position": 1, "family": "ጸ", "order": 261 },
    { "key": "ጹ", "value": "xu", "position": 2, "family": "ጸ", "order": 262 },
    { "key": "ጺ", "value": "xi", "position": 3, "family": "ጸ", "order": 263 },
    { "key": "ጻ", "value": "xa", "position": 4, "family": "ጸ", "order": 264 },
    { "key": "ጼ", "value": "xie", "position": 5, "family": "ጸ", "order": 265 },
    { "key": "ጽ", "value": "x", "position": 6, "family": "ጸ", "order": 266 },
    { "key": "ጾ", "value": "xo", "position": 7, "family": "ጸ", "order": 267 },
    { "key": "ፀ", "value": "x2e", "position": 1, "family": "ፀ", "order": 268 },
    { "key": "ፁ", "value": "x2u", "position": 2, "family": "ፀ", "order": 269 },
    { "key": "ፂ", "value": "x2i", "position": 3, "family": "ፀ", "order": 270 },
    { "key": "ፃ", "value": "x2a", "position": 4, "family": "ፀ", "order": 271 },
    { "key": "ፄ", "value": "x2ie", "position": 5, "family": "ፀ", "order": 272 },
    { "key": "ፅ", "value": "x2", "position": 6, "family": "ፀ", "order": 273 },
    { "key": "ፆ", "value": "x2o", "position": 7, "family": "ፀ", "order": 274 },
    { "key": "ፈ", "value": "fe", "position": 1, "family": "ፈ", "order": 275 },
    { "key": "ፉ", "value": "fu", "position": 2, "family": "ፈ", "order": 276 },
    { "key": "ፊ", "value": "fi", "position": 3, "family": "ፈ", "order": 277 },
    { "key": "ፋ", "value": "fa", "position": 4, "family": "ፈ", "order": 278 },
    { "key": "ፌ", "value": "fie", "position": 5, "family": "ፈ", "order": 279 },
    { "key": "ፍ", "value": "f", "position": 6, "family": "ፈ", "order": 280 },
    { "key": "ፎ", "value": "fo", "position": 7, "family": "ፈ", "order": 281 },
    { "key": "ፐ", "value": "pe", "position": 1, "family": "ፐ", "order": 282 },
    { "key": "ፑ", "value": "pu", "position": 2, "family": "ፐ", "order": 283 },
    { "key": "ፒ", "value": "pi", "position": 3, "family": "ፐ", "order": 284 },
    { "key": "ፓ", "value": "pa", "position": 4, "family": "ፐ", "order": 285 },
    { "key": "ፔ", "value": "pie", "position": 5, "family": "ፐ", "order": 286 },
    { "key": "ፕ", "value": "p", "position": 6, "family": "ፐ", "order": 287 },
    { "key": "ፖ", "value": "po", "position": 7, "family": "ፐ", "order": 288 },
    { "key": "።", "value": ".", "position": 1, "family": "።", "order": 289 },
    { "key": "፡", "value": ";", "position": 1, "family": "፡", "order": 290 },
    { "key": "፣", "value": ",", "position": 1, "family": "፣", "order": 291 },
    { "key": "፥", "value": ":", "position": 1, "family": "፥", "order": 292 },
    { "key": "፤", "value": "::", "position": 1, "family": "፤", "order": 293 },
    { "key": "፦", "value": ";-", "position": 1, "family": "፦", "order": 294 },
    { "key": ".", "value": "..", "position": 1, "family": ".", "order": 295 },
    { "key": "፥", "value": "?", "position": 1, "family": "፥", "order": 296 },
    { "key": "ጐ", "value": "gue", "position": 1, "family": "ጐ", "order": 297 },
    { "key": "ጒ", "value": "gui", "position": 2, "family": "ጐ", "order": 298 },
    { "key": "ጓ", "value": "gua", "position": 3, "family": "ጐ", "order": 299 },
    { "key": "ጔ", "value": "guie", "position": 4, "family": "ጐ", "order": 300 },
    { "key": "ጕ", "value": "gW", "position": 5, "family": "ጐ", "order": 301 },
    { "key": "ሇ", "value": "hoa", "position": 1, "family":"ሇ", "order": 302 },
    { "key": "ሏ", "value": "lua", "position": 1, "family": "ሏ", "order": 303 },
    { "key": "ሗ", "value": "Hua", "position": 1, "family": "ሗ", "order": 304 },
    { "key": "ሟ", "value": "mua", "position": 1, "family": "ሟ", "order": 305 },
    { "key": "ሧ", "value": "s2ua", "position": 1, "family": "ሧ", "order": 306 },
    { "key": "ሯ", "value": "rua", "position": 1, "family": "ሯ", "order": 307 },
    { "key": "ሷ", "value": "sua", "position": 1, "family": "ሷ", "order": 308 },
    { "key": "ሿ", "value": "Sua", "position": 1, "family": "ሿ", "order": 309 },
    { "key": "ቇ", "value": "qoa", "position": 1, "family": "ቇ", "order": 310 },
    { "key": "ቧ", "value": "bua", "position": 1, "family": "ቧ", "order": 311 },
    { "key": "ቯ", "value": "vua", "position": 1, "family": "ቯ", "order": 312 },
    { "key": "ቷ", "value": "tua", "position": 1, "family": "ቷ", "order": 313 },
    { "key": "ቿ", "value": "cua", "position": 1, "family": "ቿ", "order": 314 },
    { "key": "ኗ", "value": "nua", "position": 1, "family": "ኗ", "order": 315 },
    { "key": "ኟ", "value": "Nua", "position": 1, "family": "ኟ", "order": 316 },
    { "key": "ኧ", "value": "ua", "position": 1, "family": "ኧ", "order": 317 },
    { "key": "ኯ", "value": "koa", "position": 1, "family": "ኯ", "order": 318 },
    { "key": "ዃ", "value": "Kua", "position": 1, "family": "ዃ", "order": 319 },
    { "key": "ዏ", "value": "woa", "position": 1, "family": "ዏ", "order": 320 },
    { "key": "ዟ", "value": "zua", "position": 1, "family": "ዟ", "order": 321 },
    { "key": "ዧ", "value": "Zua", "position": 1, "family": "ዧ", "order": 322 },
    { "key": "ዯ", "value": "yoa", "position": 1, "family":"ዯ", "order": 323 },
    { "key": "ዷ", "value": "dua", "position": 1, "family": "ዷ", "order": 324 },
    { "key": "ጇ", "value": "jua", "position": 1, "family": "ጇ", "order": 325 },
    { "key": "ጏ", "value": "goa", "position": 1, "family":"ጏ", "order": 326 },
    { "key": "ጧ", "value": "Tua", "position": 1, "family": "ጧ", "order": 327 },
    { "key": "ጯ", "value": "Cua", "position": 1, "family": "ጯ", "order": 328 },
    { "key": "ጷ", "value": "Pua", "position": 1, "family": "ጷ", "order": 329 },
    { "key": "ጿ", "value": "xua", "position": 1, "family": "ጿ", "order": 330 },
    { "key": "ፇ", "value": "x2ua", "position": 1, "family":  "ፇ", "order": 331 },
    { "key": "ፏ", "value": "fua", "position": 1, "family": "ፏ", "order": 332 },
    { "key": "ፗ", "value": "pua", "position": 1, "family": "ፗ", "order": 333 },
    { "key": "ዸ", "value": "d2e", "position": 1, "family":"ዸ", "order": 334 },
    { "key": "ዹ", "value": "d2u", "position": 1, "family": "ዹ", "order": 335 },
    { "key": "ዺ", "value": "d2i", "position": 1, "family": "ዺ", "order": 336 },
    { "key": "ዻ", "value": "d2a", "position": 1, "family": "ዻ", "order": 337 },
    { "key": "ዼ", "value": "d2ie", "position": 1, "family": "ዼ", "order": 338 },
    { "key": "ዽ", "value": "d2", "position": 1, "family": "ዽ", "order": 339 },
    { "key": "ዾ", "value": "d2o", "position": 1, "family":"ዾ", "order": 340 },
    { "key": "ዿ", "value": "d2ua", "position": 1, "family": "ዿ", "order": 341 },
    { "key": "ፘ", "value": "ri2", "position": 1, "family": "ፘ", "order": 342 },
    { "key": "ፙ", "value": "mi2", "position": 1, "family": "ፙ", "order": 343 },
    { "key": "ፚ", "value": "fi2", "position": 1, "family": "ፚ", "order": 344 },
    { "key": "፧", "value": "??", "position": 1, "family": "፧", "order": 345 },
    { "key": "፨", "value": "...", "position": 1, "family": "፨", "order": 346 },
    { "key": "፠", "value": "....", "position": 1, "family": "፠", "order": 347 },
    { "key": "ጘ", "value": "Ge", "position": 1, "family":"ጘ", "order": 348 },
    { "key": "ጙ", "value": "Gu", "position": 2, "family": "ጙ", "order": 349 },
    { "key": "ጚ", "value": "Gi", "position": 3, "family": "ጚ", "order": 350 },
    { "key": "ጛ", "value": "Ga", "position": 4, "family":"ጛ", "order": 351 },
    { "key": "ጜ", "value": "Gie", "position": 5, "family":"ጜ", "order": 352 },
    { "key": "ጝ", "value": "G", "position": 6, "family": "ጝ", "order": 353 },
    { "key": "ጞ", "value": "Go", "position": 7, "family": "ጞ", "order": 354 },
    { "key": "ⶓ", "value": "Gue", "position": 1, "family": "ⶓ", "order": 355 },
    { "key": "ⶔ", "value": "Gui", "position": 2, "family":"ⶔ", "order": 356 },
    { "key": "ጟ", "value": "Gua", "position": 3, "family": "ጟ", "order": 357 },
    { "key": "ⶕ", "value": "Guie", "position": 4, "family":"ⶕ", "order": 358 },
    { "key": "ⶖ", "value": "GW", "position": 5, "family": "ⶖ", "order": 359 },
    { "key": "ቘ", "value": "Que", "position": 1, "family": "ቘ", "order": 360 },
    { "key": "ቚ", "value": "Qui", "position": 2, "family": "ቚ", "order": 361 },
    { "key": "ቛ", "value": "Qua", "position": 3, "family": "ቛ", "order": 362 },
    { "key": "ቜ", "value": "Quie", "position": 4, "family":"ቜ", "order": 363 },
    { "key": "ቝ", "value": "QW", "position": 5, "family": "ቝ", "order": 364 },
    { "key": "፩", "value": "1^", "position": 1, "family": "፩", "order": 1 },
    { "key": "፪", "value": "2^", "position": 1, "family": "፪", "order": 2 },
    { "key": "፫", "value": "3^", "position": 1, "family": "፫", "order": 3 },
    { "key": "፬", "value": "4^", "position": 1, "family": "፬", "order": 4 },
    { "key": "፭", "value": "5^", "position": 1, "family": "፭", "order": 5 },
    { "key": "፮", "value": "6^", "position": 1, "family":"፮", "order": 6 },
    { "key": "፯", "value": "7^", "position": 1, "family": "፯", "order": 7 },
    { "key": "፰", "value": "8^", "position": 1, "family":"፰", "order": 8 },
    { "key": "፱", "value": "9^", "position": 1, "family": "፱", "order": 9 },
    { "key": "፲", "value": "1^0", "position": 1, "family": "፲", "order": 1 },
    { "key": "፳", "value": "2^0", "position": 1, "family": "፳", "order": 2 },
    { "key": "፴", "value": "3^0", "position": 1, "family": "፴", "order": 3 },
    { "key": "፵", "value": "4^0", "position": 1, "family": "፵", "order": 4 },
    { "key": "፶", "value": "5^0", "position": 1, "family": "፶", "order": 5 },
    { "key": "፷", "value": "6^0", "position": 1, "family":"፷", "order": 6 },
    { "key": "፸", "value": "7^0", "position": 1, "family": "፸", "order": 7 },
    { "key": "፹", "value": "8^0", "position": 1, "family": "፹", "order": 8 },
    { "key": "፺", "value": "9^0", "position": 1, "family": "፺", "order": 9 }
  ]
end_possess_excludes=['ይ','ካ','ኻ','ኪ','ኺ','ኩም','ኹም','ክን','ኽን'
    ,'2','4','ም','ን','ና','ታት','ትካ','ትኪ','ትኩም','ትክን',
    'ቱ','ታ','ቶም','ን','ትና','ትካ','ኩም','ክን']
front_excludes=['ን','ብ']

all_tigrina_verb_to_bes=[
    'እቲ',       'እዚ',      'እቲኦም',    'እቶም',      'እዚኦም',     'እቲኤን',
    'እተን',      'እዚኤን',    'እዘን',     'እቲኣቶም',    'እቶም',      'እቲኣተን',
    'እተን',      'እዚኣቶም',   'እዚኦም',    'እዞም',      'ነቲ',       'ነቶም',
    'ነተን',      'ነታ',      'ነቲኦም',    'ነቲአን',     'ነቲኣ',      'ነቲኣቶም',
    'ነቲኣተን',    'ንስኻ',     'ንስኺ',     'ንሱ',       'ንሳ',       'ኣነ',
    'ንሶም',      'ንሰን',     'ንሳቶም',    'ንሳተን',     'ንስኹም',     'ንስኽን',
    'ንስኻትኩም',   'ንስኻትክን',  'ንሕና',     'ኣለኹ',      'ኣለኻ',      'ኣለኺ',
    'ኣለኹም',     'ኣለኽን',    'ኣሎ',      'ኣላ',       'ኣለዉ',      'ኣለዋ',
    'ኣለና',      'ይግባእ',    'ግድን',     'ክኽእል',     'ክትክእል',    'ክትክእሊ',
    'ክትክእሉ',    'ክትክእላ',   'ክትክእል',   'ክኽእሉ',     'ክኽእላ',     'ክንክእል',
    'ኣይምኾንካን',  'ኣይምኾንኩን', 'ኣይምኾነን',  'ኣይምኾነትን',  'ኣይምኾንኪን',  'ኣይምኾንክንን',
    'ኣይምኾንኩምን', 'ኣይምኾኑን',  'ኣይምኾናን',  'ኣይምኾንናን',  'ምኾንካ',     'ምኾንኩ',
    'ምኾነ',      'ምኾነት',    'ምኾንኪ',    'ምኾንክን',    'ምኾንኩም',    'ምኾኑ',
    'ምኾና',      'ምኾንና',    'ኣይክኸውንን', 'ኣይክትከውንን', 'ኣይክትኮንን',  'ኣይክኾናን',
    'ኣይክትኮናን',  'ኣይከውንን',  'ኣይክትኮኑን', 'ኣይክትኮኑን',  'ኣይክንከውንን', 'ክኸውን',
    'ክትከውን',    'ክትኮኒ',    'ክትኮና',    'ክትኮኑ',     'ክኾኑ',      'ክኾና',
    'ክንከውን',    'ኣይኸውንን',  'ኣይትኾኑን',  'ኣይትኾናን',
    'ኣይትኸውንን',   'ኣይኾኑን',    'ኣይኾናን',    'ኣይንኸውንን',  'ድኾና',      'ድኾኑ',
    'ድኸውን',      'ዝኸውን',     'ዝኾኑ',      'ዝኾና',      'ይኸውን',     'ትኸውን',
    'ትኾኑ',       'ትኾና',      'ትኸውን',     'ይኾኑ',      'ይኾና',      'ንኸውን',
    'ኣይምኽኣልኩን',  'ኣይምኽኣልካን', 'ኣይምኽኣልክን', 'ኣይምኽኣለን',  'ኣይምኽኣለትን', 'ኣይምኽኣልኩምን',
    'ኣይምኽኣልክንን', 'ኣይምኽኣለን',  'ኣይምኽኣሉን',  'ኣይምኽኣላን',  'ኣይምኽኣልናን', 'ምኽኣልኩ',
    'ምኽኣልካ',     'ምኽኣልኪ',    'ምኽኣለ',     'ምኽኣለት',    'ምኽኣልኩም',   'ምኽኣልክን',
    'ምኽኣለ',      'ምኽኣሉ',     'ምኽኣላ',     'ምኽኣልና',    'ምኻኣልኩ',    'ምኻኣልካ',
    'ምኻኣልኪ',     'ምኻኣለ',     'ምኻኣለት',    'ምኻኣልኩም',   'ምኻኣልክን',   'ምኻኣለ',
    'ምኻኣሉ',      'ምኻኣላ',     'ምኻኣልና',    'ኣይክእልን',   'ኣይትኽእልን',  'ኣይትኽእሉን',
    'ኣይትኽእላን',   'ኣይትኽእልን',  'ኣይክእሉን',   'ኣይክእላን',   'ኣይንኽእልን',  'ከምዘይኽእል',
    'ከምዘይትኽእል',  'ከምዘይትኽእሊ', 'ከምዘይትኽእሉ', 'ከምዘይትኽእላ', 'ከምዘይኽእሉ',  'ከምዘይኽእላ',
    'ከምዘይንኽእል',  'ከምዘይክእል',  'ከምዘይትክእል', 'ከምዘይትክእሊ', 'ከምዘይትክእሉ', 'ከምዘይትክእላ',
    'ከምዘይክእሉ',   'ከምዘይክእላ',  'ከምዘይንክእል', 'ይኽእል',     'ትኽእል',     'ትኽእሉ',
    'ትኽእላ',      'ትኽእል',     'ይኽእሉ',     'ይኽእላ',     'ንኽእል',     'ከምዝኽእል',
    'ከምትኽእል',    'ከምትኽእሊ',   'ከምትኽእሉ',   'ከምትኽእላ',   'ከምዝኽእሉ',   'ከምዝኽእላ',
    'ከምንኽእል',    'ከምዝክእል',   'ከምትክእል',   'ከምትክእሊ',   'ከምትክእሉ',   'ከምትክእላ',
    'ከምዝክእሉ',    'ከምዝክእላ',   'ከምንክእል',   'ኣይነበረንን',
    'ኣይነበረካን',  'ኣይነበረክን',  'ኣይነበርኩምን',  'ኣይነበረክንን',  'ኣይነበሮን',   'ኣይነበራን',
    'ኣይነበሮምን',  'ኣይነበረንን',  'ኣይነበረናን',   'ኔርኒ',       'ኔርካ',      'ኔርኪ',
    'ኔርኩም',     'ኔርክን',     'ኔርዎ',       'ኔርዋ',       'ኔርዎም',     'ኔርወን',
    'ኔርና',      'ኔሩኒ',      'ኔሩካ',       'ኔሩኪ',       'ኔሩኩም',     'ኔሩክን',
    'ኔሩዎ',      'ኔሩዋ',      'ኔሩዎም',      'ኔሩወን',      'ኔሩና',      'ነሩኒ',
    'ነሩካ',      'ነሩኪ',      'ነሩኩም',      'ነሩክን',      'ነሩዎ',      'ነሩዋ',
    'ነሩዎም',     'ነሩወን',     'ነሩና',       'ነይሩኒ',      'ነይሩካ',     'ነይሩኪ',
    'ነይሩኩም',    'ነይሩክን',    'ነይሩዎ',      'ነይሩዋ',      'ነይሩዎም',    'ነይሩወን',
    'ነይሩና',     'የብለይን',    'የብልካን',     'የብልክን',     'የብልኩምን',   'የብልክንን',
    'የብሉን',     'የብላን',     'የብሎምን',     'የብለንን',     'የብልናን',    'ኣለኒ',
    'ኣለካ',      'ኣለኪ',      'ኣለኩም',      'ኣለክን',      'ኣለዎ',      'ኣለዋ',
    'ኣለዎም',     'ኣለወን',     'ኣለና',       'ኣይክህልወካን',  'ኣይክህልወኒን', 'ኣይክህልዎን',
    'ኣይክህልዋን',  'ኣይክህልወኪን', 'ኣይክህልወኩምን', 'ኣይክህልወክንን', 'ኣይክህልዎምን', 'ኣይክህልወንን',
    'ኣይክህልወናን', 'ክህልወካ',    'ክህልወኒ',     'ክህልዎ',      'ክህልዋ',     'ክህልወኪ',
    'ክህልወኩም',   'ክህልወክን',   'ክህልዎም',     'ክህልወን',     'ክህልወና',    'ኣይነበርኩን',
    'ኣይነበርካን',  'ኣይነበርክን',  'ኣይነበርኩምን',  'ኣይነበርክን',   'ኣይነበረን',   'ኣይነበረትን',
    'ኣይነበሩን',   'ኣይነበራን',   'ኣይነበርናን',   'ኔረ',
    'ኔርካ',    'ኔርኪ',    'ኔርኩም',    'ኔርክን',    'ኔሩ',    'ኔራ',
    'ኔሮም',    'ኔረን',    'ኔርና',     'ነረ',      'ነርካ',   'ነርኪ',
    'ነርኩም',   'ነርክን',   'ነሩ',      'ነራ',      'ነሮም',   'ነረን',
    'ነርና',    'ነይረ',    'ነይርካ',    'ነይርኪ',    'ነይርኩም', 'ነይርክን',
    'ነይሩ',    'ነይራ',    'ነይሮም',    'ነይረን',    'ነይርና',  'ኣይኮንኩን',
    'ኣይኮንካን', 'ኣይኮንክን', 'ኣይኮንኩምን', 'ኣይኮንክንን', 'ኣይኮነን', 'ኣይኮንክን',
    'ኣይኮኑን',  'ኣይኮናን',  'ኣይኮንናን',  'ት',       'ክ',     'ይ',
    'ዝ',      'ኢየ',     'ኢኻ',      'ኢኺ',      'ኢኹም',   'ኢኽን',
    'ኢዩ',     'ኢያ',     'ኢዮም',     'ኢየን',     'ኢና',    'ዝነበርካ',
    'ዝነበርኪ',  'ዝነበርኩም', 'ዝነበርክን',  'ዝነበረ',    'ዝነበረት', 'ዝነበርኩ',
    'ዝነበሩ',   'ዝነበራ',   'ዝነበርና',   'ዘለኻ',     'ዘለኺ',   'ዘለኹም',
    'ዘለኽን',   'ዘሎ',     'ዘላ',      'ዘለኹ',     'ዘለዉ',   'ዘለዋ',
    'ዘለና',    'ከለኻ',    'ከለኺ',     'ከለኹም',    'ከለኽን',  'ከሎ',
    'ከላ',     'ከለኹ',    'ከለዉ',     'ከለዋ',     'ከለና',   'ዶ',
    'ድየ',     'ዲኻ',     'ዲኺ',      'ዲኹም',     'ዲኽን',   'ድዩ',
    'ድያ',     'ድዮም',    'ድየን',     'ዲና',      'ዲየ',    'ድኻ',
    'ድኺ',     'ድኹም',    'ድኽን',     'ዲዩ',
    'ዲያ',        'ዲዮም',       'ዲየን',        'ድና',         'ዝኸውን',
    'ርሕቐት',      'ምስ',        'ንመን',        'እንታይ',       'ኣበይ',
    'በየን',       'በየናይ',      'በበይ',        'ናበይ',        'ካበይ',
    'nabeyenay', 'ናበየናይ',     'ከመይ',        'ብኸመይ',       'ብከመይ',
    'መዓስ',       'መን',        'ክንደይ',       'ኣየናይ',       'ስለምንታይ',
    'ክንደይ ዝኸውን', 'መበል ክንደይ',  'ምስ መን',      'ዘይኮንኩ',      'ዘይኮንካ',
    'ዘይኮንኪ',     'ዘይኮንኩም',    'ዘይኮንክን',     'ዘይኮነ',       'ዘይኮነት',
    'ዘይኮኑ',      'ዘይኮና',      'ዘይኮንና',      'እንተኾይነ',     'እንተኾይንካ',
    'እንተኾይንኪ',   'እንተኾይንኩም',  'እንተኾይንክን',   'እንተኾይኑ',     'እንተኾይና',
    'እንተኾኑ',     'እንተኾና',     'እንተኾይና',     'እንተኾነ',      'እንተኮይነ',
    'እንተኮይንካ',   'እንተኮይንኪ',   'እንተኮይንኩም',   'እንተኮይንክን',   'እንተኮይኑ',
    'እንተኮይና',    'እንተኮይኖም',   'እንተኮይነን',    'እንተኮይንና',    'እንተኾይነ',
    'እንተኾይንካ',   'እንተኾይንኪ',   'እንተኾይንኩም',   'እንተኾይንክን',   'እንተኾይኑ',
    'እንተኾይና',    'እንተኾይኖም',   'እንተኾይነን',    'እንተኾይንና',    'ካብዘይኮንኩ',
    'ካብዘይኮንካ',   'ካብዘይኮንኪ',   'ካብዘይኮንኩም',   'ካብዘይኮንክን',   'ካብዘይኮነ',
    'ካብዘይኮነት',   'ካብዘይኮኑ',    'ካብዘይኮና',     'ካብዘይኮንና',    'እንተዘይኮይነ',
    'እንተዘይኮይንካ', 'እንተዘይኮይንኪ', 'እንተዘይኮይንኩም', 'እንተዘይኮይንክን', 'እንተዘይኮይኑ',
    'እንተዘይኮይና',  'እንተዘይኮይኖም', 'እንተዘይኮይነን',  'እንተዘይኮይንና',  'እንተዘይኮንኩ',
    'እንተዘይኮንካ',  'እንተዘይኮንኪ',  'እንተዘይኮንኩም',  'እንተዘይኮንክን',  'እንተዘይኮነ',
    'እንተዘይኮነት',  'እንተዘይኮኑ',   'እንተዘይኮና',    'እንተዘይኮንና',   'ካብኮንኩ',
    'ካብኮንካ',    'ካብኮንኪ',    'ካብኮንኩም', 'ካብኮንክን',  'ካብኮነ',    'ካብኮነት',
    'ካብኮኑ',     'ካብኮና',     'ካብኮንና',  'ዘይምዃነይ',  'ዘይምዃንካ',  'ዘይምዃንኪ',
    'ዘይምዃንኩም',  'ዘይምዃንክን',  'ዘይምዃኑ',  'ዘይምዃና',   'ዘይምዃኖም',  'ዘይምዃነን',
    'ዘይምዃና',    'ኮንኩ',      'ኮንካ',    'ኮንኪ',     'ኮንኩም',    'ኮንክን',
    'ኮነ',       'ኮነት',      'ኮኑ',     'ኮና',      'ኮንና',     'ኮይነ',
    'ኮይንካ',     'ኮይንኪ',     'ኮይንኩም',  'ኮይንክን',   'ኮይኑ',     'ኮይና',
    'ኮይኖም',     'ኮይነን',     'ኮይንና',   'ከይኮንኩ',   'ከይኮንካ',   'ከይኮንኪ',
    'ከይኮንኩም',   'ከይኮንክን',   'ከይኮነ',   'ከይኮነት',   'ከይኮኑ',    'ከይኮና',
    'ከይኮንና',    'ዘይከኣልኩ',   'ዘይከኣልካ', 'ዘይከኣልኪ',  'ዘይከኣልኩም', 'ዘይከኣልክን',
    'ዘይከኣለ',    'ዘይከኣለት',   'ዘይከኣሉ',  'ዘይከኣላ',   'ዘይከኣልና',  'ከኣልኩ',
    'ከኣልካ',     'ከኣልኪ',     'ከኣልኩም',  'ከኣልክን',   'ከኣለ',     'ከኣለት',
    'ከኣሉ',      'ከኣላ',      'ከኣልና',   'ዘይምኽኣለይ', 'ዘይምኽኣልካ', 'ዘይምኽኣልኪ',
    'ዘይምኽኣልኩም', 'ዘይምኽኣልክን', 'ዘይምኽኣሉ', 'ዘይምኽኣላ',  'ዘይምኽኣሎም', 'ዘይምኽኣለን',
    'ዘይምኽኣልና',  'ዘይምኽኣል',   'ዘይክእል',  'ዘይትኽእል',  'ዘይትኽእሊ',  'ዘይትኽእሉ',
    'ዘይትኽእላ',   'ዘይክእል',    'ዘይትኽእል', 'ዘይኽእሉ',   'ዘይክእላ',   'ዘይንኽእል',
    'ከይከኣልኩ',   'ከይክኣልካ',   'ከይክኣልኪ', 'ከይክኣልኩም', 'ከይክኣልክን', 'ከይክኣለ',
    'ከይክኣለት',   'ከይክኣሉ',    'ከይክኣላ',  'ከይክኣልና',
    'ከይከኣልኩ ከለኹ',   'ከይክኣልካ ከለኻ',   'ከይክኣልኪ ከለኺ',
    'ከይክኣልኩም ከለኹም', 'ከይክኣልክን ከለኽን', 'ከይክኣለ ከሎ',
    'ከይክኣለት ከላ',    'ከይክኣሉ ከለዉ',    'ከይክኣላ ከለዋ',
    'ከይክኣልና ከለና',   'ጸኒሐ',          'ጸኒሕካ',
    'ጸኒሕኪ',         'ጸኒሕኩም',        'ጸኒሕክን',
    'ጸኒሑ',          'ጸኒሓ',          'ጸኒሖም',
    'ጸኒሐን',         'ጸኒሕና',         'ኣይጸናሕኩን',
    'ኣይጸናሕካን',      'ኣይጸናሕክን',      'ኣይጸናሕኩምን',
    'ኣይጸናሕክንን',     'ኣይጸንሐን',       'ኣይጸነሐትን',
    'ኣይጸንሑን',       'ኣይጸንሓን',       'ኣይጸናሕናን',
    'ነበርኩ',         'ነበርካ',         'ነበርኪ',
    'ነበርኩም',        'ነበርክን',        'ነበረ',
    'ነበረት',         'ነበሩ',          'ነበራ',
    'ነበርና'
]

all_front_remove_collection = [
    'ኣይ',    'ዘይ',    'ከይ',    'ከተ',    'ከነ', 
    'ኸይ',    'ንዘይ',   'ንከይ',   'ንኸይ',   'ብዝ', 
    'ብም',    'ከምዝ',   'ኣብዝ',   'ኣብዘይ',  'ከምድ',
    'ከም',    'ከም',    'ከም',    'ዝ',     'ዘ',  
    'ም',     'ብዘይ',   'ብዘይም',  'ዘይም',   'ምስ',
    'ምስዝ',   'ምስት',   'እንተ',   'እንተዝ',  'እንተን',
    'ምስዘይ',  'ከምዘይ',   
    'እንተዘይ', 'ኣምበይ',
    'ኣምበይም', 'እንዳ'
]
negatives=['ኣይ',    'ዘይ',    'ከይ','ኸይ',    'ንዘይ',   'ንከይ',   'ንኸይ','ኣብዘይ','ብዘይ', 'ብዘይም',  'ዘይም','ምስዘይ','ከምዘይ','እንተዘይ', 'ኣምበይ','ኣምበይም']

special_words_identification = {
    "negatives": ["1460222", "1820222", "1510222", "1580222", "1480133094", "148013309401820222"]
}
word_ends_ley_Collection=[
    'ካሉ',   'ካላ',   'ካሎም',  'ካለን',  'ካልና',  'ካለይ',  'ኩምሉ',  'ኩምላ',
    'ኩምሎም', 'ኩምለን', 'ኩምልና', 'ኩምለይ', 'ክሉ',   'ክላ',   'ክሎም',  'ክለን',
    'ክልና',  'ክለይ',  'ክናሉ',  'ክናላ',  'ክናሎም', 'ክናለን', 'ክናልና', 'ክናለይ',
    'ክናሉ',  'ክናላ',  'ክናሎም', 'ክናለን', 'ክናልና', 'ክናለይ', 'ሉ',    'ላ',
    'ሎም',   'ለን',   'ልና',   'ለይ',   'ልካ',   'ልኩም',  'ልኪ',   'ልክን',
    'ትሉ',   'ትላ',   'ትሎም',  'ትለን',  'ትልና',  'ትለይ',  'ካላ',   'ትልኩም',
    'ትልኪ',  'ትልክን', 'ምሉ',   'ምላ',   'ምሎም',  'ምለን',  'ምልና',  'ምለይ',
    'ምልካ',  'ምልኩም', 'ምልኪ',  'ምልክን', 'ናሉ',   'ናላ',   'ናሎም',  'ናለን',
    'ናልና',  'ናለይ',  'ናልካ',  'ናልኩም', 'ናልኪ',  'ናልክን', 'ናሉ',   'ናላ',
    'ናሎም',  'ናለን',  'ናልኩም', 'ኩምለይ', 'ናልካ',  'ናልኩም', 'ናልኪ',  'ናክን',
    'ሉ',    'ላ',    'ሎም',   'ለን',   'ልኩም',  'ካኒ', 'ልካ',   'ልኩም',
    'ልኪ',   'ልክን'
]
word_ends_collection= [
'ካዮ',  'ካያ',  'ካዮም',  'ካየን',  'ካና',   'ካኒ',   'ኩሞ',  'ኩማ',
'ኩሞም', 'ኩመን', 'ኩምና',  'ኩምኒ',  'ኪዮ',   'ኪያ',   'ክዮም', 'ክየን',
'ክና',  'ክኒ',  'ክንኦ',  'ክንኣ',  'ክንኦም', 'ክንአን', 'ክናና', 'ክናኒ',
'ክንኦ', 'ክንኣ', 'ክንኦም', 'ክንአን', 'ክናና',  'ክናኒ',  'ዎ',   'ዋ',
'ዎም',  'ወን',  'ና',    'ኒ',    'ካ',    'ኩም',   'ኪ',   'ክን',
'ቶ',   'ታ',   'ቶም',   'ተን',   'ትና',   'ትኒ',   'ትካ',  'ትኩም',
'ትኪ',  'ትክን', 'ሞ',    'ማ',    'ሞም',   'መን',   'ምና',  'ምኒ',
'ምኻ',  'ምኹም', 'ምኺ',   'ምኽን',  'ንኦ',   'ንኣ',   'ንኦም', 'ንአን',
'ናና',  'ናኒ',  'ናኻ',   'ናኹም',  'ናኺ',   'ናኽን',  'ናዮ',  'ናያ',
'ናዮም', 'ናየን', 'ናኩም',  'ናካ',   'ናካ',   'ናኩም',  'ናኪ',  'ናክን',
'ዮ',   'ያ',   'ዮም',   'የን',   'ኩም', 'ካኒ','ካ',   'ኩም',
'ኪ',   'ክን'
]
word_ends_with_future_and_present_tense_data=[
    '7',   '4',   'ም',  'ን',  'ና',  'ኒ',  'ዎ',  'ዋ',  'ዎም',
    'ወን', 'ና',  'ኒ',  'ዮ',  'ያ',  'ዮም', 'የን', 'ና',  'ኒ',
    'ኦ',  'ኣ',  'ኦም', 'አን', 'ና',  'ኒ',  'ኦ',  'ኣ',  'ኦም',
    'አን', 'ና',  'ኒ',  '7',   '4',   'ም',  'ን',  'ና',  'ኒ',
    'ካ',  'ኩም', 'ኪ',  'ክን', '7',   '4',   'ም',  'ን',  'ና',
    'ኒ',  'ካ',  'ኩም', 'ኪ',  'ክን', 'ዎ',   'ዋ',   'ዎም',  'ወን',
    'ና',  'ኒ',  'ኻ',  'ኹም', 'ኺ',  'ኽን', 'ኦ',  'ኣ',  'ኦም',
    'አን', 'ና',  'ኒ',  'ኻ',  'ኹም', 'ኺ',  'ኽን', '7',   '4',
    'ም',  'የን', 'ኩም', 'ካ',  'ካ',  'ኩም', 'ኪ',  'ክን', '7',
    '4',   'ም',  'ን',  'ኩም', 'ኒ',  'ካ',  'ኩም', 'ኪ',  'ክን'
]

word_ends_with_future_and_present_tense_ley_data = [
    'ሉ',  'ላ',   'ሎም',  'ለን',  'ልና',  'ለይ',  'ሉ',  'ላ',
    'ሎም', 'ለን',  'ልና',  'ለይ',  'ሉ',   'ላ',   'ሎም', 'ለን',
    'ልና', 'ለይ',  'ሉ',   'ላ',   'ሎም',  'ለን',  'ልና', 'ለይ',
    '4ሉ',  '4ላ',   '4ሎም',  '4ለን',  '4ልና',  '4ለይ',  '1ሉ',  '1ላ',
    'ሎም', 'ለን',  'ልና',  'ለይ',  'ልካ',  'ልኩም', 'ልኪ', 'ልክን',
    'ሉ',  'ላ',   'ሎም',  'ለን',  'ልና',  'ለይ',  'ልካ', 'ልኩም',
    'ልኪ', 'ልክን', 'ሉ',   'ላ',   'ሎም',  'ለን',  'ልና', 'ለይ',
    'ልካ', 'ልኹም', 'ልኺ',  'ልኽን', 'ሉ',   'ላ',   'ሎም', 'ለን',
    'ልና', 'ለይ',  'ልካ',  'ልኩም', 'ልኪ',  'ልክን', 'ሉ',  'ላ',
    'ሎም', 'ለን',  'ልኩም', 'ለይ',  'ልካ',  'ልኩም', 'ልኪ', 'ልክን',
    'ሉ',  'ላ',   'ሎም',  'ለን',  'ልኩም', 'ለይ',  'ልካ', 'ልኩም',
    'ልኪ', 'ልክን'
]
alphabet_info={
    'family_positions':family_positions,
    'tigrina_alphabets':tigrina_alphabets,
    'tigrina_with_crosponding_english_aphabets':tigrina_english_aphabets,
    'tigrina_alphabet_for_coding':alphabet_structure,
    'family_start_to_end_positions':family_start_to_end_positions,
    'special_words_identification':special_words_identification,
    'begining_word_additions':begining_word_additions,
    'last_word_additions':last_word_additions,
    'all_tigrina_verb_to_bes':all_tigrina_verb_to_bes,
    'end_possess_excludes':end_possess_excludes,
    'front_excludes':front_excludes,
    'all_front_remove_collection':all_front_remove_collection,
    'negatives':negatives,
    'word_ends_ley_Collection':word_ends_ley_Collection,
    'word_ends_collection':word_ends_collection,
    'word_ends_with_future_and_present_tense_data':word_ends_with_future_and_present_tense_data,
    'word_ends_with_future_and_present_tense_ley_data':word_ends_with_future_and_present_tense_ley_data,
}
def get_family_alphabets(alphabet_index):
    global tigrina_english_aphabets
    # Find the family value associated with the given key
    matching_entry = next((item for item in tigrina_english_aphabets if item.get("key") == alphabet_index), None)
    
    if matching_entry is None:
        return {}  # Return an empty dictionary if no matching key is found
    
    # Get the family value
    family = matching_entry.get("family")
    
    if not family:
        return {}  # Return an empty dictionary if no family is found
    
    # Find all items with the same family value
    matching_family_alphabets = [item for item in tigrina_english_aphabets if item.get("family") == family]
    
    # Sort by position
    sorted_alphabets = sorted(matching_family_alphabets, key=lambda x: x["position"])
    
    # Create the result dictionary with positions as keys
    position_mapping = {
        1: 'first',
        2: 'second',
        3: 'third',
        4: 'fourth',
        5: 'fifth',
        6: 'sixth',
        7: 'seventh'
    }
    result = {position_mapping.get(item["position"], f'position_{item["position"]}'): item["key"] for item in sorted_alphabets}
    return result



           
def get_object_by_key_value(key_value):
    for obj in tigrina_english_aphabets:
        if obj['key'] == key_value:
            return obj
    return None
def get_family(text):
    text = list(text)
    families = []
    positions = []
    family_positions=[]
    for key in text:
        getAlpha = next((value for value in tigrina_english_aphabets if value['key'] == key), None)
        if getAlpha is not None:
            family=getAlpha['family']
            result = get_object_by_key_value(family)
            if result is not None:
                family_positions.append(str(result['order']))
                if getAlpha is not None:
                    families.append(getAlpha['family'])
                    positions.append(getAlpha['position'])
    info = {
        'families': ''.join(families),
        'families_positions':''.join(family_positions),
        'text_positions': ''.join(map(str, positions)),
        'text': ''.join(text)
    }
    return info


# Usage

class tg_alphabet:
    alphabets_info = alphabet_info
    @staticmethod
    def get_alphabet(alphabet):
        try:
            myresult = get_family_alphabets(alphabet)
            return myresult
        except Exception as error:
            return "There is something wrong." + str(error)
        
    @staticmethod
    def get_family(text):
        try:
            result = get_family(text)
            return result
        except Exception as error:
            return "There is something wrong." + str(error)

# You can create an instance of the NounInfo class
extract_alphabets = tg_alphabet()