# Generated by Django 5.1.2 on 2025-01-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_chatmetric_metadata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatmetric",
            old_name="confidence_score",
            new_name="embedding_tokens",
        ),
        migrations.RenameField(
            model_name="chatmetric",
            old_name="token_usage",
            new_name="llm_completion_tokens",
        ),
        migrations.RemoveField(
            model_name="chatmetric",
            name="response_time",
        ),
        migrations.AddField(
            model_name="chatmetric",
            name="llm_prompt_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatmetric",
            name="total_llm_tokens",
            field=models.IntegerField(default=0),
        ),
    ]
