# Generated by Django 5.1.2 on 2025-01-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0004_rename_confidence_score_chatmetric_embedding_tokens_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="aggregatedchatmetric",
            old_name="total_token_usage",
            new_name="embedding_tokens",
        ),
        migrations.RemoveField(
            model_name="aggregatedchatmetric",
            name="avg_confidence_score",
        ),
        migrations.RemoveField(
            model_name="aggregatedchatmetric",
            name="avg_response_time",
        ),
        migrations.AddField(
            model_name="aggregatedchatmetric",
            name="llm_completion_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aggregatedchatmetric",
            name="llm_prompt_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aggregatedchatmetric",
            name="total_llm_tokens",
            field=models.IntegerField(default=0),
        ),
    ]
