# coding: utf-8

"""
    Gmail API

    The Gmail API lets you view and manage Gmail mailbox data like threads, messages, and labels.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.language_settings import LanguageSettings  # noqa: E501
from swagger_client.rest import ApiException


class TestLanguageSettings(unittest.TestCase):
    """LanguageSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLanguageSettings(self):
        """Test LanguageSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.language_settings.LanguageSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
