# coding: utf-8

"""
    Gmail API

    The Gmail API lets you view and manage Gmail mailbox data like threads, messages, and labels.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Filter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'action': 'FilterAction',
        'criteria': 'FilterCriteria',
        'id': 'str'
    }

    attribute_map = {
        'action': 'action',
        'criteria': 'criteria',
        'id': 'id'
    }

    def __init__(self, action=None, criteria=None, id=None):  # noqa: E501
        """Filter - a model defined in Swagger"""  # noqa: E501
        self._action = None
        self._criteria = None
        self._id = None
        self.discriminator = None
        if action is not None:
            self.action = action
        if criteria is not None:
            self.criteria = criteria
        if id is not None:
            self.id = id

    @property
    def action(self):
        """Gets the action of this Filter.  # noqa: E501


        :return: The action of this Filter.  # noqa: E501
        :rtype: FilterAction
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this Filter.


        :param action: The action of this Filter.  # noqa: E501
        :type: FilterAction
        """

        self._action = action

    @property
    def criteria(self):
        """Gets the criteria of this Filter.  # noqa: E501


        :return: The criteria of this Filter.  # noqa: E501
        :rtype: FilterCriteria
        """
        return self._criteria

    @criteria.setter
    def criteria(self, criteria):
        """Sets the criteria of this Filter.


        :param criteria: The criteria of this Filter.  # noqa: E501
        :type: FilterCriteria
        """

        self._criteria = criteria

    @property
    def id(self):
        """Gets the id of this Filter.  # noqa: E501

        The server assigned ID of the filter.  # noqa: E501

        :return: The id of this Filter.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Filter.

        The server assigned ID of the filter.  # noqa: E501

        :param id: The id of this Filter.  # noqa: E501
        :type: str
        """

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Filter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Filter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
