
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-10T18:00:13+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4e1885d87f4d91a1c1bfb300ba1926d1f0ce5a1b",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
