CREATE TABLE company_module_map (
    company_id VARCHAR primary KEY REFERENCES company(company_id),
    module_feed JSONB,
    module_connect JSONB,
    module_survey JSONB,
    module_contest JSONB,
    module_recognition JSONB,
    module_events JSONB,
    module_analytics JSONB,
    module_shop JSONB,
    module_notification JSONB,
    hris_intergration JSONB,
    custom_branding JSONB,
    custom_color_theme JSONB,
    authentication_mode JSONB,
    feed_story JSONB,
    feed_community JSONB,
    feed_recognition JSONB,
    feed_polls JSONB,
    feed_profanity_check JSONB,
    connect_dms JSONB,
    connect_space JSONB,
    connect_huddle JSONB,
    connect_huddle_global_limit JSONB,
    connect_meet JSONB,
    connect_meet_global_limit JSONB,
    connect_threads JSONB,
    connect_campaigns JSONB,
    survey_recurring JSONB,
    notification_emails JSONB,
    notification_sms JSONB,
    notification_push JSONB
);