# coding: utf-8

"""
    Live Data People API

    This API provides information about people as observed by Live Data

    The version of the OpenAPI document: 1.0
    Contact: support@livedatatechnologies.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ldt_people_client_staging.models.find_request_matches_inner_fields_inner import FindRequestMatchesInnerFieldsInner

class TestFindRequestMatchesInnerFieldsInner(unittest.TestCase):
    """FindRequestMatchesInnerFieldsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FindRequestMatchesInnerFieldsInner:
        """Test FindRequestMatchesInnerFieldsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FindRequestMatchesInnerFieldsInner`
        """
        model = FindRequestMatchesInnerFieldsInner()
        if include_optional:
            return FindRequestMatchesInnerFieldsInner(
                field_name = '',
                search_term = ''
            )
        else:
            return FindRequestMatchesInnerFieldsInner(
        )
        """

    def testFindRequestMatchesInnerFieldsInner(self):
        """Test FindRequestMatchesInnerFieldsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
