# coding: utf-8

"""
    Live Data People API

    This API provides information about people as observed by Live Data

    The version of the OpenAPI document: 1.0
    Contact: support@livedatatechnologies.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ldt_people_client_staging.models.company import Company

class TestCompany(unittest.TestCase):
    """Company unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Company:
        """Test Company
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Company`
        """
        model = Company()
        if include_optional:
            return Company(
                id = '',
                name = '',
                location = '',
                linkedin = '',
                ticker = '',
                type = 'Privately Held',
                address = '',
                country = '',
                domain = '',
                employee_count = 1.337,
                industry = '',
                sic_codes = [
                    ''
                    ],
                ultimate_parent = ldt_people_client_staging.models.ultimate_parent_company.UltimateParentCompany(
                    id = '', 
                    name = '', 
                    linkedin = '', 
                    ticker = '', 
                    domain = '', )
            )
        else:
            return Company(
        )
        """

    def testCompany(self):
        """Test Company"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
