# coding: utf-8

"""
    Live Data People API

    This API provides information about people as observed by Live Data

    The version of the OpenAPI document: 1.0
    Contact: support@livedatatechnologies.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ldt_people_client_staging.models.verify200_response_inner_current_position import Verify200ResponseInnerCurrentPosition

class TestVerify200ResponseInnerCurrentPosition(unittest.TestCase):
    """Verify200ResponseInnerCurrentPosition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Verify200ResponseInnerCurrentPosition:
        """Test Verify200ResponseInnerCurrentPosition
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Verify200ResponseInnerCurrentPosition`
        """
        model = Verify200ResponseInnerCurrentPosition()
        if include_optional:
            return Verify200ResponseInnerCurrentPosition(
                company_name = '',
                company_linkedin = '',
                title = ''
            )
        else:
            return Verify200ResponseInnerCurrentPosition(
        )
        """

    def testVerify200ResponseInnerCurrentPosition(self):
        """Test Verify200ResponseInnerCurrentPosition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
