# coding: utf-8

"""
    Airtable API

    OpenAPI spec for Airtable's REST API  # noqa: E501

    OpenAPI spec version: 2024-12-27
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.field_options16_choices import FieldOptions16Choices  # noqa: E501
from swagger_client.rest import ApiException


class TestFieldOptions16Choices(unittest.TestCase):
    """FieldOptions16Choices unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFieldOptions16Choices(self):
        """Test FieldOptions16Choices"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.field_options16_choices.FieldOptions16Choices()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
