#    game.pyi    #
# Written By GQX #

from multiprocessing.queues import Queue
from multiprocessing import Process

class Py2048(Process):
    def __init__(
        self,
        name : str = ...,
        #size : int = ...,
        operateAPI : Queue = ...,
        getPuzzleAPI : Queue = ...,
        endless : bool = ...,
        debug : bool = ...
    ) -> None: ...
    
    def __main(
        self,
        size : int = ...,
        name : str = ...,
        operateAPI : Queue = ...,
        getPuzzleAPI : Queue = ...,
        endless : bool = ...,
        debug : bool = ...
    ) -> None: ...

    def __drawRestartButton(self) -> None: ...

    def __drawScoreList(self) -> None: ...

    def __drawTitleWhenFailed(self) -> None: ...

    def __randAddBlock(self) -> None: ...

    def __drawBackGround(self) -> None: ...

    def __blitBlocks(self) -> None: ...

    def __moveBlocks(self) -> None: ...

    def __updateStatus(self) -> None: ...

    def __drawBottomBar(self) -> None: ...

    def __updateWindowInfo(self) -> None: ...

    def __updatePictures(self) -> None: ...

    def __reInitialize(self) -> None: ...

    def __startGame(self) -> None: ...
    
    def __quit(self) -> None: ...

    def __print(self, text : str) -> None: ...

    def __call__(self) -> None: ...

    def __getattr__(self, name : str) -> None: ...

    def __str__(self) -> str: ...

    def __hash__(self) -> int: ...
