# Generated by Django 3.2.18 on 2023-03-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kapt_apidae", "0002_auto_20221109_1652"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="camper_van_car_park",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Camper van car park"
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="is_destination",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Is destination"
            ),
        ),
        migrations.AlterField(
            model_name="monthdayopeningchoices",
            name="monthday",
            field=models.CharField(
                choices=[
                    ("D_1ER_LUNDI", "Premier Lundi"),
                    ("D_2EME_LUNDI", "Second Lundi"),
                    ("D_3EME_LUNDI", "Troisième Lundi"),
                    ("D_4EME_LUNDI", "Quatrième Lundi"),
                    ("D_DERNIER_LUNDI", "Dernier Lundi"),
                    ("D_1ER_MARDI", "Premier Mardi"),
                    ("D_2EME_MARDI", "Second Mardi"),
                    ("D_3EME_MARDI", "Troisième Mardi"),
                    ("D_4EME_MARDI", "Quatrième Mardi"),
                    ("D_DERNIER_MARDI", "Dernier Mardi"),
                    ("D_1ER_MERCREDI", "Premier Mercredi"),
                    ("D_2EME_MERCREDI", "Second Mercredi"),
                    ("D_3EME_MERCREDI", "Troisième Mercredi"),
                    ("D_4EME_MERCREDI", "Quatrième Mercredi"),
                    ("D_DERNIER_MERCREDI", "Dernier Mercredi"),
                    ("D_1ER_JEUDI", "Premier Jeudi"),
                    ("D_2EME_JEUDI", "Second Jeudi"),
                    ("D_3EME_JEUDI", "Troisième Jeudi"),
                    ("D_4EME_JEUDI", "Quatrième Jeudi"),
                    ("D_DERNIER_JEUDI", "Dernier Jeudi"),
                    ("D_1ER_VENDREDI", "Premier Vendredi"),
                    ("D_2EME_VENDREDI", "Second Vendredi"),
                    ("D_3EME_VENDREDI", "Troisième Vendredi"),
                    ("D_4EME_VENDREDI", "Quatrième Vendredi"),
                    ("D_DERNIER_VENDREDI", "Dernier Vendredi"),
                    ("D_1ER_SAMEDI", "Premier Samedi"),
                    ("D_2EME_SAMEDI", "Second Samedi"),
                    ("D_3EME_SAMEDI", "Troisième Samedi"),
                    ("D_4EME_SAMEDI", "Quatrième Samedi"),
                    ("D_DERNIER_SAMEDI", "Dernier Samedi"),
                    ("D_1ER_DIMANCHE", "Premier Dimanche"),
                    ("D_2EME_DIMANCHE", "Second Dimanche"),
                    ("D_3EME_DIMANCHE", "Troisième Dimanche"),
                    ("D_4EME_DIMANCHE", "Quatrième Dimanche"),
                    ("D_DERNIER_DIMANCHE", "Dernier Dimanche"),
                ],
                max_length=500,
                verbose_name="Opening days",
            ),
        ),
        migrations.AlterField(
            model_name="multimediafile",
            name="locale",
            field=models.CharField(choices=[], max_length=500, verbose_name="Language"),
        ),
    ]
