# Generated by Django 3.2.18 on 2023-03-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kapt_apidae", "0003_auto_20230314_0923"),
    ]

    operations = [
        migrations.AlterField(
            model_name="touristicobject",
            name="adjustable_rooms_quantity",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Adjustable rooms quantity"
            ),
        ),
    ]
