# Generated by Django 3.2.22 on 2023-12-15 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("kapt_apidae", "0006_auto_20231215_1652"),
    ]
    operations = [
        migrations.AddField(
            model_name="touristicobject",
            name="kapt_catalog_activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="apidae_touristic_objects",
                to="kapt_catalog.activity",
                verbose_name="kapt-catalog Activity",
            ),
        ),
        migrations.AlterField(
            model_name="touristicobject",
            name="aspect",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "HIVER"),
                    (2, "ETE"),
                    (3, "HANDICAP"),
                    (4, "TOURISME_AFFAIRES"),
                    (5, "GROUPES"),
                    (6, "PRESTATAIRE_ACTIVITES"),
                ],
                db_index=True,
                null=True,
                verbose_name="Aspect",
            ),
        ),
    ]
