# coding: utf-8

"""
    Airtable API

    OpenAPI spec for Airtable's REST API  # noqa: E501

    OpenAPI spec version: 2024-12-27
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.record_response_with_comments import RecordResponseWithComments  # noqa: E501
from swagger_client.rest import ApiException


class TestRecordResponseWithComments(unittest.TestCase):
    """RecordResponseWithComments unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecordResponseWithComments(self):
        """Test RecordResponseWithComments"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.record_response_with_comments.RecordResponseWithComments()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
