# Generated by Django 5.1.2 on 2024-12-31 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bento", "0003_loadedbento_config"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loadedbento",
            options={"get_latest_by": "updated_at"},
        ),
    ]
