# Generated by Django 5.1.1 on 2024-09-23 23:06

import bloomerp.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bloomerp", "0019_alter_documenttemplatestyling_styling"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttemplate",
            name="template",
            field=bloomerp.models.fields.TextEditorField(default=""),
        ),
        migrations.AlterField(
            model_name="documenttemplatestyling",
            name="styling",
            field=bloomerp.models.fields.CodeField(default="", language="scss"),
        ),
    ]
