# coding: utf-8

"""
    Gmail API

    The Gmail API lets you view and manage Gmail mailbox data like threads, messages, and labels.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.watch_response import WatchResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestWatchResponse(unittest.TestCase):
    """WatchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWatchResponse(self):
        """Test WatchResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.watch_response.WatchResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
