"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
class RuleConverter:
    """Converts YAML rules to Markdown format for different AI assistants."""
    def __init__(self, template_dir: str) -> None:
        """
        Initialize the converter.

        Args:
            template_dir: Directory containing YAML templates
        """
        ...
    
    def convert_to_markdown(self, assistant_type: str, output_dir: str) -> None:
        """
        Convert YAML configuration to Markdown format.

        Args:
            assistant_type: Type of assistant (cursor/windsurf/cli)
            output_dir: Directory to save output files
        """
        ...
    


