# Generated by Django 5.1.4 on 2025-01-11 22:50

import crimsonslate_portfolio.validators
import django.core.validators
import django.db.models.deletion
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimsonslate_portfolio', '0002_alter_media_source_alter_media_thumb_mediasourcefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediasourcefile',
            name='media',
        ),
        migrations.AlterField(
            model_name='media',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimsonslate_portfolio.mediasourcefile'),
        ),
        migrations.AlterField(
            model_name='media',
            name='thumb',
            field=models.ImageField(blank=True, default=None, null=True, storage=storages.backends.s3.S3Storage(bucket_name='crimsonslate-bucket', location='media/', region_name='us-east-1', verify=False), upload_to='thumb/', validators=[django.core.validators.validate_image_file_extension], verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='mediacategory',
            name='cover',
            field=models.ImageField(blank=True, default=None, null=True, storage=storages.backends.s3.S3Storage(bucket_name='crimsonslate-bucket', location='media/', region_name='us-east-1', verify=False), upload_to='category/', verbose_name='cover image'),
        ),
        migrations.AlterField(
            model_name='mediasourcefile',
            name='file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(bucket_name='crimsonslate-bucket', location='media/', region_name='us-east-1', verify=False), upload_to='', validators=[crimsonslate_portfolio.validators.validate_media_file_extension]),
        ),
    ]
