
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-13T13:52:56+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e5c2e8efc15471e71ca9cd593117d3096c959c53",
 "version": "0.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
