# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from seerep.pb import point_cloud_2_pb2 as point__cloud__2__pb2
from seerep.pb import query_pb2 as query__pb2
from seerep.pb import server_response_pb2 as server__response__pb2


class PointCloudServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPointCloud2 = channel.unary_stream(
                '/seerep.pb.PointCloudService/GetPointCloud2',
                request_serializer=query__pb2.Query.SerializeToString,
                response_deserializer=point__cloud__2__pb2.PointCloud2.FromString,
                )
        self.TransferPointCloud2 = channel.unary_unary(
                '/seerep.pb.PointCloudService/TransferPointCloud2',
                request_serializer=point__cloud__2__pb2.PointCloud2.SerializeToString,
                response_deserializer=server__response__pb2.ServerResponse.FromString,
                )


class PointCloudServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPointCloud2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferPointCloud2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PointCloudServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPointCloud2': grpc.unary_stream_rpc_method_handler(
                    servicer.GetPointCloud2,
                    request_deserializer=query__pb2.Query.FromString,
                    response_serializer=point__cloud__2__pb2.PointCloud2.SerializeToString,
            ),
            'TransferPointCloud2': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferPointCloud2,
                    request_deserializer=point__cloud__2__pb2.PointCloud2.FromString,
                    response_serializer=server__response__pb2.ServerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'seerep.pb.PointCloudService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PointCloudService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPointCloud2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/seerep.pb.PointCloudService/GetPointCloud2',
            query__pb2.Query.SerializeToString,
            point__cloud__2__pb2.PointCloud2.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TransferPointCloud2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/seerep.pb.PointCloudService/TransferPointCloud2',
            point__cloud__2__pb2.PointCloud2.SerializeToString,
            server__response__pb2.ServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
