# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transform.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from seerep.pb import vector3_pb2 as vector3__pb2
from seerep.pb import quaternion_pb2 as quaternion__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftransform.proto\x12\tseerep.pb\x1a\rvector3.proto\x1a\x10quaternion.proto\"]\n\tTransform\x12\'\n\x0btranslation\x18\x01 \x01(\x0b\x32\x12.seerep.pb.Vector3\x12\'\n\x08rotation\x18\x02 \x01(\x0b\x32\x15.seerep.pb.Quaternionb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transform_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRANSFORM._serialized_start=63
  _TRANSFORM._serialized_end=156
# @@protoc_insertion_point(module_scope)
