from typing import Literal

WEBSOCKET_OPENED = "WEBSOCKET_OPENED"
WEBSOCKET_SYSTEM_ONLINE = "online"
WEBSOCKET_SYSTEM_MAINTENANCE = "maintenance"
WEBSOCKET_SYSTEM_CANCEL_ONLY = "cancel_only"
WEBSOCKET_SYSTEM_POST_ONLY = "post_only"
WEBSOCKET_SYSTEM_LIMIT_ONLY = "limit_only"
WEBSOCKET_CLOSED = "WEBSOCKET_CLOSED"
WEBSOCKET_AUTHENTICATED = "WEBSOCKET_AUTHENTICATED"

Status = Literal["WEBSOCKET_OPENED", "WEBSOCKET_CLOSED", "WEBSOCKET_AUTHENTICATED", "online", "maintenance", "cancel_only", "post_only", "limit_only"]
