# coding: utf-8

"""
    Airtable API

    OpenAPI spec for Airtable's REST API  # noqa: E501

    OpenAPI spec version: 2024-12-27
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FieldOptions15(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'field_id_in_linked_table': 'str',
        'formula': 'str',
        'is_valid': 'bool',
        'referenced_field_ids': 'list[str]',
        'result': 'object'
    }

    attribute_map = {
        'field_id_in_linked_table': 'fieldIdInLinkedTable',
        'formula': 'formula',
        'is_valid': 'isValid',
        'referenced_field_ids': 'referencedFieldIds',
        'result': 'result'
    }

    def __init__(self, field_id_in_linked_table=None, formula=None, is_valid=None, referenced_field_ids=None, result=None):  # noqa: E501
        """FieldOptions15 - a model defined in Swagger"""  # noqa: E501
        self._field_id_in_linked_table = None
        self._formula = None
        self._is_valid = None
        self._referenced_field_ids = None
        self._result = None
        self.discriminator = None
        if field_id_in_linked_table is not None:
            self.field_id_in_linked_table = field_id_in_linked_table
        if formula is not None:
            self.formula = formula
        if is_valid is not None:
            self.is_valid = is_valid
        if referenced_field_ids is not None:
            self.referenced_field_ids = referenced_field_ids
        if result is not None:
            self.result = result

    @property
    def field_id_in_linked_table(self):
        """Gets the field_id_in_linked_table of this FieldOptions15.  # noqa: E501

        The id of the field in the linked table  # noqa: E501

        :return: The field_id_in_linked_table of this FieldOptions15.  # noqa: E501
        :rtype: str
        """
        return self._field_id_in_linked_table

    @field_id_in_linked_table.setter
    def field_id_in_linked_table(self, field_id_in_linked_table):
        """Sets the field_id_in_linked_table of this FieldOptions15.

        The id of the field in the linked table  # noqa: E501

        :param field_id_in_linked_table: The field_id_in_linked_table of this FieldOptions15.  # noqa: E501
        :type: str
        """

        self._field_id_in_linked_table = field_id_in_linked_table

    @property
    def formula(self):
        """Gets the formula of this FieldOptions15.  # noqa: E501

        The rollup formula  # noqa: E501

        :return: The formula of this FieldOptions15.  # noqa: E501
        :rtype: str
        """
        return self._formula

    @formula.setter
    def formula(self, formula):
        """Sets the formula of this FieldOptions15.

        The rollup formula  # noqa: E501

        :param formula: The formula of this FieldOptions15.  # noqa: E501
        :type: str
        """

        self._formula = formula

    @property
    def is_valid(self):
        """Gets the is_valid of this FieldOptions15.  # noqa: E501

        Whether the rollup is valid  # noqa: E501

        :return: The is_valid of this FieldOptions15.  # noqa: E501
        :rtype: bool
        """
        return self._is_valid

    @is_valid.setter
    def is_valid(self, is_valid):
        """Sets the is_valid of this FieldOptions15.

        Whether the rollup is valid  # noqa: E501

        :param is_valid: The is_valid of this FieldOptions15.  # noqa: E501
        :type: bool
        """

        self._is_valid = is_valid

    @property
    def referenced_field_ids(self):
        """Gets the referenced_field_ids of this FieldOptions15.  # noqa: E501

        The ids of any fields referenced in the rollup formula  # noqa: E501

        :return: The referenced_field_ids of this FieldOptions15.  # noqa: E501
        :rtype: list[str]
        """
        return self._referenced_field_ids

    @referenced_field_ids.setter
    def referenced_field_ids(self, referenced_field_ids):
        """Sets the referenced_field_ids of this FieldOptions15.

        The ids of any fields referenced in the rollup formula  # noqa: E501

        :param referenced_field_ids: The referenced_field_ids of this FieldOptions15.  # noqa: E501
        :type: list[str]
        """

        self._referenced_field_ids = referenced_field_ids

    @property
    def result(self):
        """Gets the result of this FieldOptions15.  # noqa: E501

        The computed result of the rollup  # noqa: E501

        :return: The result of this FieldOptions15.  # noqa: E501
        :rtype: object
        """
        return self._result

    @result.setter
    def result(self, result):
        """Sets the result of this FieldOptions15.

        The computed result of the rollup  # noqa: E501

        :param result: The result of this FieldOptions15.  # noqa: E501
        :type: object
        """

        self._result = result

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FieldOptions15, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FieldOptions15):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
