# Generated by Django 5.1.1 on 2024-09-15 22:11

import bloomerp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bloomerp", "0003_kpi_created_at_kpi_updated_at_sqlquery_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to=bloomerp.models.File.upload_to),
        ),
    ]
