
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-13T14:07:49+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "478788cd88340cc43884cc866a31420d1398a2ad",
 "version": "0.6.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
