# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: upheavalprotocol/prices/tx.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'upheavalprotocol/prices/tx.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v4_proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from v4_proto.cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from v4_proto.cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2
from v4_proto.upheavalprotocol.prices import market_param_pb2 as upheavalprotocol_dot_prices_dot_market__param__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n upheavalprotocol/prices/tx.proto\x12\x17upheavalprotocol.prices\x1a\x14gogoproto/gogo.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x17\x63osmos/msg/v1/msg.proto\x1a*upheavalprotocol/prices/market_param.proto\"\x90\x01\n\x15MsgCreateOracleMarket\x12+\n\tauthority\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressString\x12:\n\x06params\x18\x02 \x01(\x0b\x32$.upheavalprotocol.prices.MarketParamB\x04\xc8\xde\x1f\x00:\x0e\x82\xe7\xb0*\tauthority\"\x1f\n\x1dMsgCreateOracleMarketResponse\"\xa2\x01\n\x15MsgUpdateMarketPrices\x12X\n\x14market_price_updates\x18\x01 \x03(\x0b\x32:.upheavalprotocol.prices.MsgUpdateMarketPrices.MarketPrice\x1a/\n\x0bMarketPrice\x12\x11\n\tmarket_id\x18\x01 \x01(\r\x12\r\n\x05price\x18\x02 \x01(\x04\"\x1f\n\x1dMsgUpdateMarketPricesResponse\"\x95\x01\n\x14MsgUpdateMarketParam\x12+\n\tauthority\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressString\x12@\n\x0cmarket_param\x18\x02 \x01(\x0b\x32$.upheavalprotocol.prices.MarketParamB\x04\xc8\xde\x1f\x00:\x0e\x82\xe7\xb0*\tauthority\"\x1e\n\x1cMsgUpdateMarketParamResponse2\xfc\x02\n\x03Msg\x12|\n\x12UpdateMarketPrices\x12..upheavalprotocol.prices.MsgUpdateMarketPrices\x1a\x36.upheavalprotocol.prices.MsgUpdateMarketPricesResponse\x12|\n\x12\x43reateOracleMarket\x12..upheavalprotocol.prices.MsgCreateOracleMarket\x1a\x36.upheavalprotocol.prices.MsgCreateOracleMarketResponse\x12y\n\x11UpdateMarketParam\x12-.upheavalprotocol.prices.MsgUpdateMarketParam\x1a\x35.upheavalprotocol.prices.MsgUpdateMarketParamResponseB>Z<github.com/upheavalprotocol/v4-chain/protocol/x/prices/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'upheavalprotocol.prices.tx_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z<github.com/upheavalprotocol/v4-chain/protocol/x/prices/types'
  _globals['_MSGCREATEORACLEMARKET'].fields_by_name['authority']._loaded_options = None
  _globals['_MSGCREATEORACLEMARKET'].fields_by_name['authority']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_MSGCREATEORACLEMARKET'].fields_by_name['params']._loaded_options = None
  _globals['_MSGCREATEORACLEMARKET'].fields_by_name['params']._serialized_options = b'\310\336\037\000'
  _globals['_MSGCREATEORACLEMARKET']._loaded_options = None
  _globals['_MSGCREATEORACLEMARKET']._serialized_options = b'\202\347\260*\tauthority'
  _globals['_MSGUPDATEMARKETPARAM'].fields_by_name['authority']._loaded_options = None
  _globals['_MSGUPDATEMARKETPARAM'].fields_by_name['authority']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_MSGUPDATEMARKETPARAM'].fields_by_name['market_param']._loaded_options = None
  _globals['_MSGUPDATEMARKETPARAM'].fields_by_name['market_param']._serialized_options = b'\310\336\037\000'
  _globals['_MSGUPDATEMARKETPARAM']._loaded_options = None
  _globals['_MSGUPDATEMARKETPARAM']._serialized_options = b'\202\347\260*\tauthority'
  _globals['_MSGCREATEORACLEMARKET']._serialized_start=180
  _globals['_MSGCREATEORACLEMARKET']._serialized_end=324
  _globals['_MSGCREATEORACLEMARKETRESPONSE']._serialized_start=326
  _globals['_MSGCREATEORACLEMARKETRESPONSE']._serialized_end=357
  _globals['_MSGUPDATEMARKETPRICES']._serialized_start=360
  _globals['_MSGUPDATEMARKETPRICES']._serialized_end=522
  _globals['_MSGUPDATEMARKETPRICES_MARKETPRICE']._serialized_start=475
  _globals['_MSGUPDATEMARKETPRICES_MARKETPRICE']._serialized_end=522
  _globals['_MSGUPDATEMARKETPRICESRESPONSE']._serialized_start=524
  _globals['_MSGUPDATEMARKETPRICESRESPONSE']._serialized_end=555
  _globals['_MSGUPDATEMARKETPARAM']._serialized_start=558
  _globals['_MSGUPDATEMARKETPARAM']._serialized_end=707
  _globals['_MSGUPDATEMARKETPARAMRESPONSE']._serialized_start=709
  _globals['_MSGUPDATEMARKETPARAMRESPONSE']._serialized_end=739
  _globals['_MSG']._serialized_start=742
  _globals['_MSG']._serialized_end=1122
# @@protoc_insertion_point(module_scope)
