add_test([=[Mapping.ScalarTest]=]  /home/jbernard/workspace/next/sardine/test/sardinetest [==[--gtest_filter=Mapping.ScalarTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mapping.ScalarTest]=]  PROPERTIES WORKING_DIRECTORY /home/jbernard/workspace/next/sardine/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mapping.Span]=]  /home/jbernard/workspace/next/sardine/test/sardinetest [==[--gtest_filter=Mapping.Span]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mapping.Span]=]  PROPERTIES WORKING_DIRECTORY /home/jbernard/workspace/next/sardine/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mapping.SubSpan]=]  /home/jbernard/workspace/next/sardine/test/sardinetest [==[--gtest_filter=Mapping.SubSpan]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mapping.SubSpan]=]  PROPERTIES WORKING_DIRECTORY /home/jbernard/workspace/next/sardine/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mapping.Vector]=]  /home/jbernard/workspace/next/sardine/test/sardinetest [==[--gtest_filter=Mapping.Vector]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mapping.Vector]=]  PROPERTIES WORKING_DIRECTORY /home/jbernard/workspace/next/sardine/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mapping.VectorToSpan]=]  /home/jbernard/workspace/next/sardine/test/sardinetest [==[--gtest_filter=Mapping.VectorToSpan]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mapping.VectorToSpan]=]  PROPERTIES WORKING_DIRECTORY /home/jbernard/workspace/next/sardine/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mapping.StringView]=]  /home/jbernard/workspace/next/sardine/test/sardinetest [==[--gtest_filter=Mapping.StringView]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mapping.StringView]=]  PROPERTIES WORKING_DIRECTORY /home/jbernard/workspace/next/sardine/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mapping.String]=]  /home/jbernard/workspace/next/sardine/test/sardinetest [==[--gtest_filter=Mapping.String]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mapping.String]=]  PROPERTIES WORKING_DIRECTORY /home/jbernard/workspace/next/sardine/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mapping.Container]=]  /home/jbernard/workspace/next/sardine/test/sardinetest [==[--gtest_filter=Mapping.Container]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mapping.Container]=]  PROPERTIES WORKING_DIRECTORY /home/jbernard/workspace/next/sardine/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mapping.MdSpan]=]  /home/jbernard/workspace/next/sardine/test/sardinetest [==[--gtest_filter=Mapping.MdSpan]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mapping.MdSpan]=]  PROPERTIES WORKING_DIRECTORY /home/jbernard/workspace/next/sardine/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mapping.MdSpanStrided]=]  /home/jbernard/workspace/next/sardine/test/sardinetest [==[--gtest_filter=Mapping.MdSpanStrided]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mapping.MdSpanStrided]=]  PROPERTIES WORKING_DIRECTORY /home/jbernard/workspace/next/sardine/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Url.ScalarTest]=]  /home/jbernard/workspace/next/sardine/test/sardinetest [==[--gtest_filter=Url.ScalarTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Url.ScalarTest]=]  PROPERTIES WORKING_DIRECTORY /home/jbernard/workspace/next/sardine/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Url.StringTest]=]  /home/jbernard/workspace/next/sardine/test/sardinetest [==[--gtest_filter=Url.StringTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Url.StringTest]=]  PROPERTIES WORKING_DIRECTORY /home/jbernard/workspace/next/sardine/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Cache.ScalarTest]=]  /home/jbernard/workspace/next/sardine/test/sardinetest [==[--gtest_filter=Cache.ScalarTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Cache.ScalarTest]=]  PROPERTIES WORKING_DIRECTORY /home/jbernard/workspace/next/sardine/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Cache.StringTest]=]  /home/jbernard/workspace/next/sardine/test/sardinetest [==[--gtest_filter=Cache.StringTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Cache.StringTest]=]  PROPERTIES WORKING_DIRECTORY /home/jbernard/workspace/next/sardine/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Json.Scalar]=]  /home/jbernard/workspace/next/sardine/test/sardinetest [==[--gtest_filter=Json.Scalar]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Json.Scalar]=]  PROPERTIES WORKING_DIRECTORY /home/jbernard/workspace/next/sardine/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Box.ManagedIntegerBox]=]  /home/jbernard/workspace/next/sardine/test/sardinetest [==[--gtest_filter=Box.ManagedIntegerBox]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Box.ManagedIntegerBox]=]  PROPERTIES WORKING_DIRECTORY /home/jbernard/workspace/next/sardine/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[View.ClosingDimension]=]  /home/jbernard/workspace/next/sardine/test/sardinetest [==[--gtest_filter=View.ClosingDimension]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[View.ClosingDimension]=]  PROPERTIES WORKING_DIRECTORY /home/jbernard/workspace/next/sardine/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[View.MdViewClosingDimension]=]  /home/jbernard/workspace/next/sardine/test/sardinetest [==[--gtest_filter=View.MdViewClosingDimension]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[View.MdViewClosingDimension]=]  PROPERTIES WORKING_DIRECTORY /home/jbernard/workspace/next/sardine/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ProducerConsumer.HostIntegerProCon]=]  /home/jbernard/workspace/next/sardine/test/sardinetest [==[--gtest_filter=ProducerConsumer.HostIntegerProCon]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ProducerConsumer.HostIntegerProCon]=]  PROPERTIES WORKING_DIRECTORY /home/jbernard/workspace/next/sardine/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ProducerConsumer.RingIntegerProCon]=]  /home/jbernard/workspace/next/sardine/test/sardinetest [==[--gtest_filter=ProducerConsumer.RingIntegerProCon]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ProducerConsumer.RingIntegerProCon]=]  PROPERTIES WORKING_DIRECTORY /home/jbernard/workspace/next/sardine/test SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  sardinetest_TESTS Mapping.ScalarTest Mapping.Span Mapping.SubSpan Mapping.Vector Mapping.VectorToSpan Mapping.StringView Mapping.String Mapping.Container Mapping.MdSpan Mapping.MdSpanStrided Url.ScalarTest Url.StringTest Cache.ScalarTest Cache.StringTest Json.Scalar Box.ManagedIntegerBox View.ClosingDimension View.MdViewClosingDimension ProducerConsumer.HostIntegerProCon ProducerConsumer.RingIntegerProCon)
