# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: upheavalprotocol/delaymsg/query.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'upheavalprotocol/delaymsg/query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v4_proto.google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from v4_proto.upheavalprotocol.delaymsg import delayed_message_pb2 as upheavalprotocol_dot_delaymsg_dot_delayed__message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%upheavalprotocol/delaymsg/query.proto\x12\x19upheavalprotocol.delaymsg\x1a\x1cgoogle/api/annotations.proto\x1a/upheavalprotocol/delaymsg/delayed_message.proto\"\"\n QueryNextDelayedMessageIdRequest\"D\n!QueryNextDelayedMessageIdResponse\x12\x1f\n\x17next_delayed_message_id\x18\x01 \x01(\r\"!\n\x13QueryMessageRequest\x12\n\n\x02id\x18\x01 \x01(\r\"R\n\x14QueryMessageResponse\x12:\n\x07message\x18\x01 \x01(\x0b\x32).upheavalprotocol.delaymsg.DelayedMessage\"3\n\x1bQueryBlockMessageIdsRequest\x12\x14\n\x0c\x62lock_height\x18\x01 \x01(\r\"3\n\x1cQueryBlockMessageIdsResponse\x12\x13\n\x0bmessage_ids\x18\x01 \x03(\r2\xb8\x04\n\x05Query\x12\xc0\x01\n\x14NextDelayedMessageId\x12;.upheavalprotocol.delaymsg.QueryNextDelayedMessageIdRequest\x1a<.upheavalprotocol.delaymsg.QueryNextDelayedMessageIdResponse\"-\x82\xd3\xe4\x93\x02\'\x12%/upheavalprotocol/v4/delaymsg/next_id\x12\x9e\x01\n\x07Message\x12..upheavalprotocol.delaymsg.QueryMessageRequest\x1a/.upheavalprotocol.delaymsg.QueryMessageResponse\"2\x82\xd3\xe4\x93\x02,\x12*/upheavalprotocol/v4/delaymsg/message/{id}\x12\xca\x01\n\x0f\x42lockMessageIds\x12\x36.upheavalprotocol.delaymsg.QueryBlockMessageIdsRequest\x1a\x37.upheavalprotocol.delaymsg.QueryBlockMessageIdsResponse\"F\x82\xd3\xe4\x93\x02@\x12>/upheavalprotocol/v4/delaymsg/block/message_ids/{block_height}B@Z>github.com/upheavalprotocol/v4-chain/protocol/x/delaymsg/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'upheavalprotocol.delaymsg.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/upheavalprotocol/v4-chain/protocol/x/delaymsg/types'
  _globals['_QUERY'].methods_by_name['NextDelayedMessageId']._loaded_options = None
  _globals['_QUERY'].methods_by_name['NextDelayedMessageId']._serialized_options = b'\202\323\344\223\002\'\022%/upheavalprotocol/v4/delaymsg/next_id'
  _globals['_QUERY'].methods_by_name['Message']._loaded_options = None
  _globals['_QUERY'].methods_by_name['Message']._serialized_options = b'\202\323\344\223\002,\022*/upheavalprotocol/v4/delaymsg/message/{id}'
  _globals['_QUERY'].methods_by_name['BlockMessageIds']._loaded_options = None
  _globals['_QUERY'].methods_by_name['BlockMessageIds']._serialized_options = b'\202\323\344\223\002@\022>/upheavalprotocol/v4/delaymsg/block/message_ids/{block_height}'
  _globals['_QUERYNEXTDELAYEDMESSAGEIDREQUEST']._serialized_start=147
  _globals['_QUERYNEXTDELAYEDMESSAGEIDREQUEST']._serialized_end=181
  _globals['_QUERYNEXTDELAYEDMESSAGEIDRESPONSE']._serialized_start=183
  _globals['_QUERYNEXTDELAYEDMESSAGEIDRESPONSE']._serialized_end=251
  _globals['_QUERYMESSAGEREQUEST']._serialized_start=253
  _globals['_QUERYMESSAGEREQUEST']._serialized_end=286
  _globals['_QUERYMESSAGERESPONSE']._serialized_start=288
  _globals['_QUERYMESSAGERESPONSE']._serialized_end=370
  _globals['_QUERYBLOCKMESSAGEIDSREQUEST']._serialized_start=372
  _globals['_QUERYBLOCKMESSAGEIDSREQUEST']._serialized_end=423
  _globals['_QUERYBLOCKMESSAGEIDSRESPONSE']._serialized_start=425
  _globals['_QUERYBLOCKMESSAGEIDSRESPONSE']._serialized_end=476
  _globals['_QUERY']._serialized_start=479
  _globals['_QUERY']._serialized_end=1047
# @@protoc_insertion_point(module_scope)
