
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-13T03:04:42+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f1d46fcf86c331b21dc199f5129f59da3bc1284e",
 "version": "2.13.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
