# Generated by Django 5.1.2 on 2024-12-18 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_testobject"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestObject",
        ),
    ]
