# Generated by Django 5.1.2 on 2024-12-28 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_kitchenaimanagement_jupyter_host"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kitchenaimodule",
            name="kitchen",
        ),
        migrations.DeleteModel(
            name="KitchenAIDependencies",
        ),
        migrations.DeleteModel(
            name="KitchenAIModule",
        ),
    ]
