CREATE TABLE company_module_map (
    company_id VARCHAR primary KEY REFERENCES company(company_id),
    module_feed VARCHAR,
    module_connect VARCHAR,
    module_survey VARCHAR,
    module_contest VARCHAR,
    module_recognition VARCHAR,
    module_events VARCHAR,
    module_analytics VARCHAR,
    module_shop VARCHAR,
    module_notification VARCHAR,
    hris_intergration VARCHAR,
    custom_branding VARCHAR,
    custom_color_theme VARCHAR,
    authentication_mode VARCHAR,
    feed_story VARCHAR,
    feed_community VARCHAR,
    feed_recognition VARCHAR,
    feed_polls VARCHAR,
    feed_profanity_check VARCHAR,
    connect_dms VARCHAR,
    connect_space VARCHAR,
    connect_huddle VARCHAR,
    connect_huddle_global_limit VARCHAR,
    connect_meet VARCHAR,
    connect_meet_global_limit VARCHAR,
    connect_threads VARCHAR,
    connect_campaigns VARCHAR,
    survey_recurring VARCHAR,
    notification_emails VARCHAR,
    notification_sms VARCHAR,
    notification_push VARCHAR
);