# Generated by Django 5.1.2 on 2025-01-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0005_rename_total_token_usage_aggregatedchatmetric_embedding_tokens_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmetric",
            name="input_text",
            field=models.TextField(default="n/a"),
        ),
        migrations.AlterField(
            model_name="chatmetric",
            name="output_text",
            field=models.TextField(default="n/a"),
        ),
    ]
