# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class Interrupt(UniversalBaseModel):
    """
    Represents an interruption in the execution flow.
    """

    value: typing.Optional[typing.Optional[typing.Any]] = None
    when: typing.Optional[typing.Literal["during"]] = None
    resumable: typing.Optional[bool] = None
    ns: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
