header_lsit = [
    # 通用头部（General Headers）
    "Cache-Control",
    "Connection",
    "Date",
    "Pragma",
    "Trailer",
    # 请求头部（Request Headers）
    "Accept",
    "Accept-Charset",
    "Accept-Encoding",
    "Accept-Language",
    "Authorization",
    "Cache-Control",
    "Connection",
    "Cookie",
    "Host",
    "If-Modified-Since",
    "If-None-Match",
    "Range",
    "Referer",
    "User-Agent",
    "X-Requested-With",
    "Content-Type",
    "Content-Length",
    "Origin",
    "Upgrade-Insecure-Requests",
    # 响应头部（Response Headers）
    "Access-Control-Allow-Origin",
    "Content-Encoding",
    "Content-Language",
    "Content-Length",
    "Content-Type",
    "Date",
    "ETag",
    "Location",
    "Server",
    "Set-Cookie",
    "WWW-Authenticate",
    # 实体头部（Entity Headers）
    "Content-Disposition",
    "Content-Type",
    "Content-Length",
    "Content-Encoding",
    "Last-Modified",
    "Expires",
    # 其他常见的自定义请求头
    "X-Frame-Options",
    "X-Content-Type-Options",
    "X-XSS-Protection",
    "X-Powered-By",
]

