
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-13T10:39:06+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "0cc06ab9fda3e5866fbd1fc4979b8a1c6da39a1b",
 "version": "0.0.30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
