# coding: utf-8

"""
    Gmail API

    The Gmail API lets you view and manage Gmail mailbox data like threads, messages, and labels.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FilterAction(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'add_label_ids': 'list[str]',
        'forward': 'str',
        'remove_label_ids': 'list[str]'
    }

    attribute_map = {
        'add_label_ids': 'addLabelIds',
        'forward': 'forward',
        'remove_label_ids': 'removeLabelIds'
    }

    def __init__(self, add_label_ids=None, forward=None, remove_label_ids=None):  # noqa: E501
        """FilterAction - a model defined in Swagger"""  # noqa: E501
        self._add_label_ids = None
        self._forward = None
        self._remove_label_ids = None
        self.discriminator = None
        if add_label_ids is not None:
            self.add_label_ids = add_label_ids
        if forward is not None:
            self.forward = forward
        if remove_label_ids is not None:
            self.remove_label_ids = remove_label_ids

    @property
    def add_label_ids(self):
        """Gets the add_label_ids of this FilterAction.  # noqa: E501

        List of labels to add to the message.  # noqa: E501

        :return: The add_label_ids of this FilterAction.  # noqa: E501
        :rtype: list[str]
        """
        return self._add_label_ids

    @add_label_ids.setter
    def add_label_ids(self, add_label_ids):
        """Sets the add_label_ids of this FilterAction.

        List of labels to add to the message.  # noqa: E501

        :param add_label_ids: The add_label_ids of this FilterAction.  # noqa: E501
        :type: list[str]
        """

        self._add_label_ids = add_label_ids

    @property
    def forward(self):
        """Gets the forward of this FilterAction.  # noqa: E501

        Email address that the message should be forwarded to.  # noqa: E501

        :return: The forward of this FilterAction.  # noqa: E501
        :rtype: str
        """
        return self._forward

    @forward.setter
    def forward(self, forward):
        """Sets the forward of this FilterAction.

        Email address that the message should be forwarded to.  # noqa: E501

        :param forward: The forward of this FilterAction.  # noqa: E501
        :type: str
        """

        self._forward = forward

    @property
    def remove_label_ids(self):
        """Gets the remove_label_ids of this FilterAction.  # noqa: E501

        List of labels to remove from the message.  # noqa: E501

        :return: The remove_label_ids of this FilterAction.  # noqa: E501
        :rtype: list[str]
        """
        return self._remove_label_ids

    @remove_label_ids.setter
    def remove_label_ids(self, remove_label_ids):
        """Sets the remove_label_ids of this FilterAction.

        List of labels to remove from the message.  # noqa: E501

        :param remove_label_ids: The remove_label_ids of this FilterAction.  # noqa: E501
        :type: list[str]
        """

        self._remove_label_ids = remove_label_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FilterAction, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FilterAction):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
