# Generated by Django 2.2.7 on 2019-11-06 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("kapt_catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessTourismService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_tourism_max_capacity",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Business tourism maximum capacity",
                    ),
                ),
                (
                    "equipped_meeting_rooms_quantity",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Equipped meeting rooms quantity",
                    ),
                ),
                (
                    "adjustable_rooms_quantity",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="Adjustable rooms quantity"
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kapt_catalog.Activity",
                        verbose_name="Activity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business tourism service",
                "verbose_name_plural": "Business tourism services",
            },
        ),
        migrations.CreateModel(
            name="MeetingRoom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Identifier"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Max capacity"
                    ),
                ),
                (
                    "area",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Area"
                    ),
                ),
                (
                    "height",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Height"
                    ),
                ),
                (
                    "natural_lighting",
                    models.BooleanField(default=False, verbose_name="Natural lighting"),
                ),
                (
                    "min_price",
                    models.FloatField(null=True, verbose_name="Minimum price"),
                ),
                (
                    "max_price",
                    models.FloatField(null=True, verbose_name="Maximum price"),
                ),
                (
                    "business_tourism_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kapt_catalog.BusinessTourismService",
                        verbose_name="Business tourism service description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting room",
                "verbose_name_plural": "Meeting rooms",
            },
        ),
        migrations.CreateModel(
            name="RoomLayout",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacity", models.PositiveSmallIntegerField(verbose_name="Capacity")),
                (
                    "layout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kapt_catalog.Characteristic",
                        verbose_name="Meeting room layout type",
                    ),
                ),
                (
                    "meeting_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kapt_catalog.MeetingRoom",
                        verbose_name="Meeting room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting room layout",
                "verbose_name_plural": "Meeting room layouts",
            },
        ),
        migrations.CreateModel(
            name="PackActivity",
            fields=[
                (
                    "activity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="kapt_catalog.Activity",
                    ),
                ),
                (
                    "number_of_days",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Number of days"
                    ),
                ),
                (
                    "number_of_nights",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Number of nights"
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="_packactivity_categories_+",
                        to="kapt_catalog.Characteristic",
                        verbose_name="Categories",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pack activity",
                "verbose_name_plural": "Pack activities",
            },
            bases=("kapt_catalog.activity",),
        ),
        migrations.AddField(
            model_name="businesstourismservice",
            name="characteristics",
            field=models.ManyToManyField(
                blank=True,
                related_name="_businesstourismservice_characteristics_+",
                to="kapt_catalog.Characteristic",
                verbose_name="Characteristics",
            ),
        ),
    ]
