# Generated by Django 2.2.24 on 2021-08-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kapt_catalog", "0013_auto_20230104_1713"),
    ]

    operations = [
        migrations.AlterField(
            model_name="BusinessTourismService",
            name="business_tourism_max_capacity",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Business tourism maximum capacity"
            ),
        ),
        migrations.AlterField(
            model_name="BusinessTourismService",
            name="equipped_meeting_rooms_quantity",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Equipped meeting rooms quantity"
            ),
        ),
        migrations.AlterField(
            model_name="BusinessTourismService",
            name="adjustable_rooms_quantity",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Adjustable rooms quantity"
            ),
        ),
    ]
