# Generated by Django 3.2.22 on 2023-12-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kapt_catalog", "0015_auto_20231222_1544"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealactivity",
            name="categories",
            field=models.ManyToManyField(
                related_name="meal_activity_categories",
                to="kapt_catalog.Characteristic",
                verbose_name="Categories",
            ),
        ),
        migrations.AlterField(
            model_name="mealactivity",
            name="specialties",
            field=models.ManyToManyField(
                related_name="meal_activity_specialties",
                to="kapt_catalog.Characteristic",
                verbose_name="Specialties",
            ),
        ),
    ]
