# Generated by Django 2.2.28 on 2024-07-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kapt_catalog", "0017_auto_20240102_1453"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structure",
            name="booking_url",
            field=models.URLField(
                blank=True, max_length=2048, null=True, verbose_name="Booking Url"
            ),
        ),
    ]
