# coding: utf-8

"""
    Airtable API

    OpenAPI spec for Airtable's REST API  # noqa: E501

    OpenAPI spec version: 2024-12-27
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.records_api import RecordsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRecordsApi(unittest.TestCase):
    """RecordsApi unit test stubs"""

    def setUp(self):
        self.api = RecordsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_airtable_records_create(self):
        """Test case for airtable_records_create

        Create records  # noqa: E501
        """
        pass

    def test_airtable_records_delete(self):
        """Test case for airtable_records_delete

        Delete record  # noqa: E501
        """
        pass

    def test_airtable_records_delete_multiple(self):
        """Test case for airtable_records_delete_multiple

        Delete multiple records  # noqa: E501
        """
        pass

    def test_airtable_records_get(self):
        """Test case for airtable_records_get

        Get record  # noqa: E501
        """
        pass

    def test_airtable_records_list(self):
        """Test case for airtable_records_list

        List records  # noqa: E501
        """
        pass

    def test_airtable_records_replace(self):
        """Test case for airtable_records_replace

        Replace record  # noqa: E501
        """
        pass

    def test_airtable_records_replace_multiple(self):
        """Test case for airtable_records_replace_multiple

        Replace multiple records  # noqa: E501
        """
        pass

    def test_airtable_records_sync_csv(self):
        """Test case for airtable_records_sync_csv

        Sync CSV data  # noqa: E501
        """
        pass

    def test_airtable_records_update(self):
        """Test case for airtable_records_update

        Update record  # noqa: E501
        """
        pass

    def test_airtable_records_update_multiple(self):
        """Test case for airtable_records_update_multiple

        Update multiple records  # noqa: E501
        """
        pass

    def test_airtable_records_upload_attachment(self):
        """Test case for airtable_records_upload_attachment

        Upload attachment  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
