"""Beam constants for the consensus"""
BEAM_HASH_SIZE = 12  # B
BEAM_AES_ENCRYPTION_KEY_SIZE = 256  # Bits
DEFAULT_HANDSHAKE_AES_KEY_SIZE = 256  # Bits
DEFAULT_AES_SALT_SIZE = 12  # B
DEFAULT_AES_GCM_NONCE_SIZE = 12  # B
DEFAULT_AES_GCM_TAG_SIZE = 16  # B

USED_ALGORITHM = "AES"
