# coding: utf-8

"""
    Moneyball

    Provides company-focused insights based on Live Data

    The version of the OpenAPI document: 1.0.0
    Contact: support@livedatatechnologies.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ldt_moneyball_client_staging.models.cp_emp_count_response_by_dept_inner_by_month_inner import CPEmpCountResponseByDeptInnerByMonthInner

class TestCPEmpCountResponseByDeptInnerByMonthInner(unittest.TestCase):
    """CPEmpCountResponseByDeptInnerByMonthInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CPEmpCountResponseByDeptInnerByMonthInner:
        """Test CPEmpCountResponseByDeptInnerByMonthInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CPEmpCountResponseByDeptInnerByMonthInner`
        """
        model = CPEmpCountResponseByDeptInnerByMonthInner()
        if include_optional:
            return CPEmpCountResponseByDeptInnerByMonthInner(
                month = '',
                count = 1.337
            )
        else:
            return CPEmpCountResponseByDeptInnerByMonthInner(
                month = '',
                count = 1.337,
        )
        """

    def testCPEmpCountResponseByDeptInnerByMonthInner(self):
        """Test CPEmpCountResponseByDeptInnerByMonthInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
