# coding: utf-8

"""
    Moneyball

    Provides company-focused insights based on Live Data

    The version of the OpenAPI document: 1.0.0
    Contact: support@livedatatechnologies.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ldt_moneyball_client_staging.models.create_employee_demo_report_request import CreateEmployeeDemoReportRequest

class TestCreateEmployeeDemoReportRequest(unittest.TestCase):
    """CreateEmployeeDemoReportRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateEmployeeDemoReportRequest:
        """Test CreateEmployeeDemoReportRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateEmployeeDemoReportRequest`
        """
        model = CreateEmployeeDemoReportRequest()
        if include_optional:
            return CreateEmployeeDemoReportRequest(
                companies = [
                    'LDCjUR,rZ#UM/?R,Fp^l6$ARj'
                    ],
                group_by = [
                    'level'
                    ],
                date_from = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                date_to = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                aggregate_type = 'monthly',
                include_grouped_companies = True
            )
        else:
            return CreateEmployeeDemoReportRequest(
                companies = [
                    'LDCjUR,rZ#UM/?R,Fp^l6$ARj'
                    ],
        )
        """

    def testCreateEmployeeDemoReportRequest(self):
        """Test CreateEmployeeDemoReportRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
