# Generated by Django 2.2.28 on 2022-11-09 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kapt_apidae", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricingperiod",
            name="type",
        ),
    ]
