# Generated by Django 3.2.24 on 2024-07-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kapt_apidae", "0008_auto_20231221_1444"),
    ]

    operations = [
        migrations.AddField(
            model_name="touristicobject",
            name="animal_friendly",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACCEPTES", "Accepted"),
                    ("NON_ACCEPTES", "Not accepted"),
                    ("NON_DISPONIBLE", "Unavailable"),
                    ("AVEC_SUPPLEMENT", "With extra fees"),
                    ("SANS_SUPPLEMENT", "Without extra fees"),
                ],
                max_length=500,
                null=True,
                verbose_name="Animal friendly",
            ),
        ),
        migrations.AddField(
            model_name="touristicobject",
            name="animal_friendly_description",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Animal friendly textual description",
            ),
        ),
        migrations.AddField(
            model_name="touristicobject",
            name="animal_friendly_further_informations",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACCEPTES", "Accepted"),
                    ("NON_ACCEPTES", "Not accepted"),
                    ("NON_DISPONIBLE", "Unavailable"),
                    ("AVEC_SUPPLEMENT", "With extra fees"),
                    ("SANS_SUPPLEMENT", "Without extra fees"),
                ],
                max_length=500,
                null=True,
                verbose_name="Animal friendly further informations",
            ),
        ),
    ]
