# Generated by Django 2.1.15 on 2020-06-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kapt_catalog", "0005_auto_20200601_0758"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingroom",
            name="area",
            field=models.IntegerField(blank=True, null=True, verbose_name="Area"),
        ),
    ]
