# Generated by Django 2.2.16 on 2020-10-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kapt_catalog", "0006_auto_20200601_0830"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="is_free",
            field=models.BooleanField(default=False, verbose_name="Is free"),
        ),
    ]
