# Generated by Django 2.2.19 on 2021-04-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kapt_catalog", "0009_merge_20210421_1111"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="website",
            field=models.URLField(
                blank=True, max_length=2048, null=True, verbose_name="Website"
            ),
        ),
    ]
