# Generated by Django 2.2.24 on 2021-08-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kapt_catalog", "0010_auto_20210421_1112"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitytranslation",
            name="name",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Name"),
        ),
    ]
