# Generated by Django 2.2.28 on 2023-01-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kapt_catalog", "0011_auto_20210806_1112"),
    ]

    operations = [
        migrations.AddField(
            model_name="structurereference",
            name="identifier",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Identifier"
            ),
        ),
    ]
