# coding: utf-8

"""
    Gmail API

    The Gmail API lets you view and manage Gmail mailbox data like threads, messages, and labels.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.modify_thread_request import ModifyThreadRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestModifyThreadRequest(unittest.TestCase):
    """ModifyThreadRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModifyThreadRequest(self):
        """Test ModifyThreadRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.modify_thread_request.ModifyThreadRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
