# coding: utf-8

"""
    Live Data Identity API

    Manage your Live Data organization and user access to your resources

    The version of the OpenAPI document: 1.0
    Contact: support@livedatatechnologies.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ldt_identity_client_staging.models.post_session_google200_response_orgs_inner import PostSessionGoogle200ResponseOrgsInner

class TestPostSessionGoogle200ResponseOrgsInner(unittest.TestCase):
    """PostSessionGoogle200ResponseOrgsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostSessionGoogle200ResponseOrgsInner:
        """Test PostSessionGoogle200ResponseOrgsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostSessionGoogle200ResponseOrgsInner`
        """
        model = PostSessionGoogle200ResponseOrgsInner()
        if include_optional:
            return PostSessionGoogle200ResponseOrgsInner(
                id = '',
                name = '',
                role = '',
                settings = None,
                customer_id = '',
                contacts_count = '',
                status = '',
                created_at = ''
            )
        else:
            return PostSessionGoogle200ResponseOrgsInner(
                id = '',
                name = '',
                role = '',
                settings = None,
                customer_id = '',
                contacts_count = '',
                status = '',
                created_at = '',
        )
        """

    def testPostSessionGoogle200ResponseOrgsInner(self):
        """Test PostSessionGoogle200ResponseOrgsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
