"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from .constants import HandType

@dataclass
class FingerBend:
  """指の曲げ具合"""
  mcp: float
  pip: float
  dip: float
  tilt: float
  ...


@dataclass
class HandBend:
  """手のデータ"""
  device_id: str
  hand_type: HandType
  thumb: FingerBend
  index: FingerBend
  middle: FingerBend
  ring: FingerBend
  little: FingerBend
  ...


def parse_hand_bend(args) -> HandBend:
  """手のデータをパースする"""
  ...

