# coding: utf-8

"""
    Airtable API

    OpenAPI spec for Airtable's REST API  # noqa: E501

    OpenAPI spec version: 2024-12-27
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.comments_api import CommentsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCommentsApi(unittest.TestCase):
    """CommentsApi unit test stubs"""

    def setUp(self):
        self.api = CommentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_airtable_comments_create(self):
        """Test case for airtable_comments_create

        Create comment  # noqa: E501
        """
        pass

    def test_airtable_comments_delete(self):
        """Test case for airtable_comments_delete

        Delete comment  # noqa: E501
        """
        pass

    def test_airtable_comments_list(self):
        """Test case for airtable_comments_list

        List comments  # noqa: E501
        """
        pass

    def test_airtable_comments_update(self):
        """Test case for airtable_comments_update

        Update comment  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
