//** USAGE
//** ==============================================================

// You can directly call this function in your app at:

//** method : `{{ method }}`
//** url    : `{{ api_url }}`

//** CONFIGURATION
//** ==============================================================

// This file is intended to work with the other generated file in
// the `~/server/api` folder

// ** For this file to work, you must have added the `{{ backend_url }}`  backend url targeting
// ** your FastApi server in your nuxt.config.ts file :
// ** The backend url is generated by the targeted FastAPI title

// You can either hardcode it as :

// defineNuxtConfig({
//      runtimeConfig: {
//      {{ backend_url }} : "http://hardcoded/url:8000"
// })

// or define an environement variable

// defineNuxtConfig({
//      runtimeConfig: {
//      {{ backend_url }} : process.env.NUXT_XXXXXXXXXX
//      }
// })
// the environement variable needs to start with NUXT_*****
