# Generated by Django 5.1.1 on 2024-12-08 22:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "test_app",
            "0022_alter_accommodation_options_alter_employee_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "bulk_change",
                    "bulk_delete",
                    "bulk_add",
                    "export",
                )
            },
        ),
    ]
