# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .mapping_computation_arguments_value import MappingComputationArgumentsValue
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class Mapping(UniversalBaseModel):
    statement_id: str
    expression_idx: int
    variable: str
    computation_name: str
    computation_arguments: typing.Dict[str, MappingComputationArgumentsValue]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
