
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-11T00:32:03+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6ed804006e5fb7570fa5e1b25e05e701567e2f76",
 "version": "1.90.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
